membase core engine: StoredValue Class Reference
StoredValue Class Reference
In-memory storage for an item.
#include <stored-value.hh>
Public Member Functions
void operator delete (void *p)
void markDirty ()
Mark this item as needing to be persisted.
void reDirty (rel_time_t dataAge)
Mark this item as dirty as of a certain time.
void markClean (rel_time_t *dataAge)
Mark this item as clean.
bool isDirty () const
True if this object is dirty.
bool isClean () const
True if this object is not dirty.
bool isExpired (time_t asOf) const
Check if this item is expired or not.
const char * getKeyBytes () const
Get the pointer to the beginning of the key.
uint8_t getKeyLen () const
Get the length of the key.
bool hasKey (const std::string &k) const
True of this item is for the given key.
const std::string getKey () const
Get this item's key.
value_t getValue () const
Get this item's value.
time_t getExptime () const
Get the expiration time of this item.
uint32_t getFlags () const
Get the client-defined flags of this item.
void setValue (value_t v, uint32_t newFlags, time_t newExp, uint64_t theCas, EPStats &stats)
Set a new value for this item.
size_t valLength ()
bool ejectValue (EPStats &stats)
bool restoreValue (value_t v, EPStats &stats)
uint64_t getCas () const
Get this item's CAS identifier.
rel_time_t getDataAge () const
Get the time of dirtiness of this item.
void setCas (uint64_t c)
Set a new CAS ID.
void lock (rel_time_t expiry)
Lock this item until the given time.
void unlock ()
Unlock this item.
bool hasId ()
True if this item has an ID.
int64_t getId ()
Get this item's ID.
void setId (int64_t to)
Set the ID for this item.
void clearId ()
Clear the ID (after disk deletion when an object was reused).
bool isPendingId ()
Is this item currently waiting to receive a new ID?
void setPendingId ()
Set this item to be pending an ID.
void clearPendingId ()
If we're still in a pending ID state, clear the state.
size_t size ()
Get the total size of this item.
bool isLocked (rel_time_t curtime)
Return true if this item is locked as of the given timestamp.
bool isResident ()
True if this value is resident in memory currently.
bool isDeleted () const
True if this object is logically deleted.
void del (EPStats &stats)
Logically delete this object.
Static Public Member Functions
static size_t sizeOf (bool small)
Get the size of a StoredValue object.
static void setMaxDataSize (EPStats &, size_t)
Set the maximum amount of data this instance can store.
static size_t getMaxDataSize (EPStats &)
Get the maximum amount of memory this instance can store.
static size_t getCurrentSize (EPStats &)
Get the current amount of of data stored.
static size_t getTotalCacheSize (EPStats &)
Get the total size of all items in the cache.
Friends
class HashTable
class StoredValueFactory
Detailed Description
In-memory storage for an item.
Member Function Documentation
void StoredValue::clearId () [inline]
Clear the ID (after disk deletion when an object was reused).
References hasId().
void StoredValue::clearPendingId () [inline]
If we're still in a pending ID state, clear the state.
References isPendingId().
Referenced by reDirty().
void StoredValue::del (EPStats & stats) [inline]
Logically delete this object.
References markDirty(), and size().
Referenced by HashTable::unlocked_softDelete().
bool StoredValue::ejectValue (EPStats & stats) [inline]
References blobval::chlen, stored_value_bodies::feature, isClean(), isDeleted(), isResident(), blobval::len, Blob::New(), feature_data::resident, size(), and valLength().
Referenced by HashTable::add(), PersistenceCallback::callback(), and PagingVisitor::visit().
uint64_t StoredValue::getCas () const [inline]
Get this item's CAS identifier.
Returns:
the cas ID for feature items, 0 for small items
References feature_data::cas, and stored_value_bodies::feature.
Referenced by HashTable::set().
size_t StoredValue::getCurrentSize (EPStats & st) [static]
Get the current amount of of data stored.
What's the total size of allocations?
References EPStats::currentSize, Atomic< T >::get(), and EPStats::memOverhead.
Referenced by ItemPager::callback(), PersistenceCallback::callback(), and sizeOf().
rel_time_t StoredValue::getDataAge () const [inline]
Get the time of dirtiness of this item.
Note that the clock loses four bits of resolution, so the timestamp only has four seconds of accuracy.
time_t StoredValue::getExptime () const [inline]
Get the expiration time of this item.
Returns:
the expiration time for feature items, 0 for small items
References feature_data::exptime, and stored_value_bodies::feature.
Referenced by isExpired().
uint32_t StoredValue::getFlags () const [inline]
Get the client-defined flags of this item.
Returns:
the flags for feature items, 0 for small items
int64_t StoredValue::getId () [inline]
Get this item's ID.
Returns:
the ID for the item; 0 if the item has no ID
const std::string StoredValue::getKey (void) const [inline]
Get this item's key.
References getKeyBytes(), and getKeyLen().
Referenced by ExpiryPagingVisitor::visit(), PagingVisitor::visit(), BackFillVisitor::visit(), and VerifyStoredVisitor::visit().
const char* StoredValue::getKeyBytes () const [inline]
Get the pointer to the beginning of the key.
References stored_value_bodies::feature, feature_data::keybytes, small_data::keybytes, and stored_value_bodies::small.
Referenced by getKey(), and hasKey().
uint8_t StoredValue::getKeyLen () const [inline]
Get the length of the key.
References stored_value_bodies::feature, feature_data::keylen, small_data::keylen, and stored_value_bodies::small.
Referenced by getKey(), hasKey(), and size().
size_t StoredValue::getMaxDataSize (EPStats & st) [static]
Get the maximum amount of memory this instance can store.
Get the maximum amount of memory available for storing data.
Returns:
the memory ceiling
References EPStats::maxDataSize.
Referenced by EventuallyPersistentEngine::initialize(), setFlushParam(), and sizeOf().
size_t StoredValue::getTotalCacheSize (EPStats & st) [static]
Get the total size of all items in the cache.
References Atomic< T >::get(), and EPStats::totalCacheSize.
Referenced by sizeOf().
value_t StoredValue::getValue () const [inline]
Get this item's value.
bool StoredValue::hasId () [inline]
True if this item has an ID.
An item always has an ID after it's been persisted.
Referenced by clearId(), setId(), and setPendingId().
bool StoredValue::hasKey (const std::string & k) const [inline]
True of this item is for the given key.
Parameters:
the key we're checking
Returns:
true if this item's key is equal to k
References getKeyBytes(), and getKeyLen().
Referenced by HashTable::unlocked_del(), and HashTable::unlocked_find().
bool StoredValue::isClean () const [inline]
True if this object is not dirty.
References isDirty().
Referenced by ejectValue(), HashTable::set(), and HashTable::unlocked_softDelete().
bool StoredValue::isDeleted () const [inline]
True if this object is logically deleted.
Referenced by HashTable::add(), ejectValue(), size(), HashTable::unlocked_find(), and valLength().
bool StoredValue::isDirty () const [inline]
True if this object is dirty.
Referenced by HashTable::add(), isClean(), and VerifyStoredVisitor::visit().
bool StoredValue::isExpired (time_t asOf) const [inline]
Check if this item is expired or not.
Parameters:
asOf the time to be compared with this item's expiry time
Returns:
true if this item's expiry time < asOf
References getExptime().
Referenced by ExpiryPagingVisitor::visit(), and PagingVisitor::visit().
bool StoredValue::isLocked (rel_time_t curtime) [inline]
Return true if this item is locked as of the given timestamp.
Parameters:
curtime lock expiration marker (usually the current time)
Returns:
true if the item is locked
References stored_value_bodies::feature, feature_data::lock_expiry, and feature_data::locked.
Referenced by HashTable::set(), and HashTable::unlocked_del().
bool StoredValue::isPendingId () [inline]
Is this item currently waiting to receive a new ID?
This is the case when it's been submitted to the storage layer and has been marked clean, but has not yet received its ID.
Returns:
true if the item is waiting for an ID.
Referenced by clearPendingId(), and setPendingId().
bool StoredValue::isResident () [inline]
True if this value is resident in memory currently.
References stored_value_bodies::feature, and feature_data::resident.
Referenced by ejectValue(), restoreValue(), valLength(), and HashTableStatVisitor::visit().
void StoredValue::lock (rel_time_t expiry) [inline]
Lock this item until the given time.
This is a NOOP for small item types.
References stored_value_bodies::feature, feature_data::lock_expiry, and feature_data::locked.
void StoredValue::markClean (rel_time_t * dataAge) [inline]
Mark this item as clean.
Parameters:
dataAge an output parameter that captures the time this item was marked dirty
Referenced by sizeOf().
void StoredValue::markDirty () [inline]
Mark this item as needing to be persisted.
References ep_current_time.
Referenced by HashTable::add(), del(), setValue(), and sizeOf().
void StoredValue::operator delete (void * p) [inline]
void StoredValue::reDirty (rel_time_t dataAge) [inline]
Mark this item as dirty as of a certain time.
This method is primarily used to mark an item as dirty again after a storage failure.
Parameters:
dataAge the previous dataAge of this record
References clearPendingId().
bool StoredValue::restoreValue (value_t v, EPStats & stats) [inline]
References stored_value_bodies::feature, isResident(), feature_data::resident, size(), and valLength().
void StoredValue::setCas (uint64_t c) [inline]
Set a new CAS ID.
This is a NOOP for small item types.
References feature_data::cas, and stored_value_bodies::feature.
void StoredValue::setId (int64_t to) [inline]
Set the ID for this item.
This is used by the persistene layer.
It is an error to set an ID on an item that already has one.
References hasId().
void StoredValue::setMaxDataSize (EPStats & st, size_t to) [static]
Set the maximum amount of data this instance can store.
Set the default number of bytes available for stored values.
While there's other overhead, this only takes into consideration the sum of StoredValue::size() values.
References EPStats::maxDataSize.
Referenced by EventuallyPersistentEngine::initialize(), and sizeOf().
void StoredValue::setPendingId () [inline]
Set this item to be pending an ID.
References hasId(), and isPendingId().
void StoredValue::setValue (value_t v, uint32_t newFlags, time_t newExp, uint64_t theCas, EPStats & stats) [inline]
Set a new value for this item.
Parameters:
v the new value
newFlags the new client-defined flags
newExp the new expiration
theCas thenew CAS identifier
References feature_data::cas, feature_data::exptime, stored_value_bodies::feature, markDirty(), and size().
Referenced by HashTable::add(), and HashTable::set().
size_t StoredValue::size () [inline]
Get the total size of this item.
Returns:
the amount of memory used by this item.
References getKeyLen(), isDeleted(), and sizeOf().
Referenced by HashTable::bucket(), del(), ejectValue(), HashTable::HashTable(), HashTable::memorySize(), restoreValue(), setValue(), sizeOf(), HashTable::unlocked_del(), HashTableStatVisitor::visit(), and HashTableDepthStatVisitor::visit().
static size_t StoredValue::sizeOf (bool small) [inline, static]
Get the size of a StoredValue object.
This method exists because the size of a StoredValue as used cannot be determined entirely at compile time due to the two different extras sections that are used.
Parameters:
small if true, we want the small variety, otherwise featured
Returns:
the size in bytes required (minus key) for a StoredValue.
References stored_value_bodies::feature, getCurrentSize(), getMaxDataSize(), getTotalCacheSize(), markClean(), markDirty(), feature_data::resident, setMaxDataSize(), and size().
Referenced by main(), and size().
void StoredValue::unlock () [inline]
Unlock this item.
References stored_value_bodies::feature, feature_data::lock_expiry, and feature_data::locked.
Referenced by HashTable::set().
size_t StoredValue::valLength () [inline]
References blobval::chlen, isDeleted(), isResident(), and blobval::len.
Referenced by ejectValue(), and restoreValue().
Friends And Related Function Documentation
friend class HashTable [friend]
friend class StoredValueFactory [friend]
Referenced by HashTable::HashTable().
The documentation for this class was generated from the following files:
stored-value.hh
stored-value.cc