membase core engine: PagingVisitor Class Reference
PagingVisitor Class Reference
As part of the ItemPager, visit all of the objects in memory and eject some within a constrained probability.
Public Member Functions
PagingVisitor (EPStats &st, double pcnt)
Construct a PagingVisitor that will attempt to evict the given percentage of objects.
void visit (StoredValue *v)
Visit an individual item within a hash table.
size_t numEjected ()
Get the number of items ejected during the visit.
size_t numFailedEjects ()
Get the number of ejection failures.
Public Attributes
std::list< std::pair< uint16_t,
std::string > > expired
Detailed Description
As part of the ItemPager, visit all of the objects in memory and eject some within a constrained probability.
Constructor & Destructor Documentation
PagingVisitor::PagingVisitor (EPStats & st, double pcnt) [inline]
Construct a PagingVisitor that will attempt to evict the given percentage of objects.
Parameters:
pcnt percentage of objects to attempt to evict (0-1)
Member Function Documentation
size_t PagingVisitor::numEjected () [inline]
Get the number of items ejected during the visit.
Referenced by ItemPager::callback().
size_t PagingVisitor::numFailedEjects () [inline]
Get the number of ejection failures.
An ejection failure is the state when an ejection was requested, but did not work for some reason (either object was dirty, or too small, or something).
Referenced by ItemPager::callback().
void PagingVisitor::visit (StoredValue * v) [inline, virtual]
Visit an individual item within a hash table.
Parameters:
v a pointer to a value in the hash table
Implements HashTableVisitor.
References VBucketVisitor::currentBucket, StoredValue::ejectValue(), expired, StoredValue::getKey(), and StoredValue::isExpired().
Member Data Documentation
std::list<std::pair<uint16_t, std::string> > PagingVisitor::expired
Referenced by ExpiredItemPager::callback(), ItemPager::callback(), and visit().
The documentation for this class was generated from the following file:
item_pager.cc