membase core engine: Flusher Class Reference
Flusher Class Reference
Manage persistence of data for an EventuallyPersistentStore.
#include <flusher.hh>
Public Member Functions
Flusher (EventuallyPersistentStore *st, Dispatcher *d)
~Flusher ()
bool stop ()
void wait ()
bool pause ()
bool resume ()
void initialize (TaskId)
void start (void)
void wake (void)
bool step (Dispatcher &, TaskId)
enum flusher_state state () const
const char * stateName () const
Detailed Description
Manage persistence of data for an EventuallyPersistentStore.
Constructor & Destructor Documentation
Flusher::Flusher (EventuallyPersistentStore * st, Dispatcher * d) [inline]
Flusher::~Flusher () [inline]
References getLogger(), stateName(), and stopped.
Member Function Documentation
void Flusher::initialize (TaskId tid)
References ep_real_time(), getLogger(), running, and store().
Referenced by step().
bool Flusher::pause (void)
References pausing.
Referenced by EventuallyPersistentStore::pauseFlusher().
bool Flusher::resume (void)
References running.
Referenced by EventuallyPersistentStore::resumeFlusher().
void Flusher::start (void)
Referenced by EventuallyPersistentStore::startFlusher().
enum flusher_state Flusher::state () const
Referenced by EventuallyPersistentEngine::initialize().
const char * Flusher::stateName () const
Referenced by EventuallyPersistentEngine::startFlusher(), step(), EventuallyPersistentEngine::stopFlusher(), and ~Flusher().
bool Flusher::step (Dispatcher & d, TaskId tid)
References getLogger(), initialize(), initializing, paused, pausing, running, Dispatcher::snooze(), stateName(), stopped, stopping, and store().
Referenced by FlusherStepper::callback().
bool Flusher::stop (void)
References stopping.
Referenced by EventuallyPersistentStore::stopFlusher().
void Flusher::wait (void)
References stopped.
Referenced by EventuallyPersistentStore::stopFlusher().
void Flusher::wake (void)
References Dispatcher::wake().
The documentation for this class was generated from the following files:
flusher.hh
flusher.cc