membase core engine: Atomic< T > Class Template Reference
Atomic< T > Class Template Reference
Holder of atomic values.
#include <atomic.hh>
Public Member Functions
Atomic (const T &initial=0)
~Atomic ()
T get () const
void set (const T &newValue)
operator T () const
void operator= (const T &newValue)
bool cas (const T &oldValue, const T &newValue)
T operator++ ()
T operator++ (int ignored)
T operator-- ()
T operator-- (int ignored)
T operator+= (T increment)
T operator-= (T decrement)
T incr (const T &increment)
T decr (const T &decrement)
T swap (const T &newValue)
T swapIfNot (const T &badValue, const T &newValue)
void setIfLess (const T &newValue)
void setIfBigger (const T &newValue)
Detailed Description
template<typename T>
class Atomic< T >
Holder of atomic values.
Constructor & Destructor Documentation
template<typename T> Atomic< T >::Atomic (const T & initial = 0) [inline]
template<typename T> Atomic< T >::~Atomic () [inline]
Member Function Documentation
template<typename T> bool Atomic< T >::cas (const T & oldValue, const T & newValue) [inline]
Referenced by Atomic< uint64_t >::setIfBigger(), Atomic< uint64_t >::setIfLess(), Atomic< uint64_t >::swap(), and Atomic< uint64_t >::swapIfNot().
template<typename T> T Atomic< T >::decr (const T & decrement) [inline]
Referenced by EventuallyPersistentStore::deleteVBucket(), EventuallyPersistentStore::reset(), and VBucket::~VBucket().
template<typename T> T Atomic< T >::get () const [inline]
Referenced by add_casted_stat(), EventuallyPersistentStore::bgFetch(), EventuallyPersistentStore::completeBGFetch(), HistogramBin< T >::count(), EventuallyPersistentStore::deleteVBucket(), StoredValue::getCurrentSize(), StoredValue::getTotalCacheSize(), EventuallyPersistentStore::getTxnSize(), VBucketHolder::isBucketDeletion(), EventuallyPersistentStore::reset(), VBucket::VBucket(), HashTable::visit(), HashTable::visitDepth(), and VBucket::~VBucket().
template<typename T> T Atomic< T >::incr (const T & increment) [inline]
Referenced by ExpiredItemPager::callback(), ItemPager::callback(), AtomicQueue< QueuedItem >::pushQueue(), and VBucket::VBucket().
template<typename T> Atomic< T >::operator T () const [inline]
template<typename T> T Atomic< T >::operator++ () [inline]
template<typename T> T Atomic< T >::operator++ (int ignored) [inline]
template<typename T> T Atomic< T >::operator+= (T increment) [inline]
template<typename T> T Atomic< T >::operator-- () [inline]
template<typename T> T Atomic< T >::operator-- (int ignored) [inline]
template<typename T> T Atomic< T >::operator-= (T decrement) [inline]
template<typename T> void Atomic< T >::operator= (const T & newValue) [inline]
template<typename T> void Atomic< T >::set (const T & newValue) [inline]
Referenced by HashTable::clear(), EPStats::reset(), VBucketHolder::setBucketDeletion(), EventuallyPersistentStore::setMinDataAge(), EventuallyPersistentStore::setQueueAgeCap(), EventuallyPersistentStore::setTxnSize(), and VBucketHolder::VBucketHolder().
template<typename T> void Atomic< T >::setIfBigger (const T & newValue) [inline]
Referenced by TapBGFetchCallback::callback(), and EventuallyPersistentStore::completeBGFetch().
template<typename T> void Atomic< T >::setIfLess (const T & newValue) [inline]
Referenced by TapBGFetchCallback::callback(), and EventuallyPersistentStore::completeBGFetch().
template<typename T> T Atomic< T >::swap (const T & newValue) [inline]
template<typename T> T Atomic< T >::swapIfNot (const T & badValue, const T & newValue) [inline]
Referenced by AtomicQueue< QueuedItem >::getAll().
The documentation for this class was generated from the following file:
atomic.hh