membase core engine: GetlExtension Class Reference
GetlExtension Class Reference
#include <ep_extension.h>
Public Member Functions
GetlExtension (EventuallyPersistentStore *kvstore, GET_SERVER_API get_server_api)
void initialize ()
bool executeGetl (int argc, token_t *argv, void *cookie, RESPONSE_HANDLER_T response_handler)
Constructor & Destructor Documentation
GetlExtension::GetlExtension (EventuallyPersistentStore * kvstore, GET_SERVER_API get_server_api)
Member Function Documentation
bool GetlExtension::executeGetl (int argc, token_t * argv, void * cookie, RESPONSE_HANDLER_T response_handler)
References Item::getCas(), Item::getData(), Item::getFlags(), Item::getKey(), EventuallyPersistentStore::getLocked(), Item::getNBytes(), GetValue::getStatus(), GetValue::getValue(), ITEM_LOCK_TIMEOUT, RememberingCallback< T >::val, and RememberingCallback< T >::waitForValue().
Referenced by ext_execute().
void GetlExtension::initialize ()
References getLogger().
Referenced by EventuallyPersistentEngine::initialize().
The documentation for this class was generated from the following files:
ep_extension.h
ep_extension.cc