membase core engine: VBucketHolder Class Reference
VBucketHolder Class Reference
#include <vbucket.hh>
Public Member Functions
VBucketHolder (size_t sz)
VBucketHolder (const RCPtr< VBucketHolder > &vbh, size_t sz)
~VBucketHolder ()
RCPtr< VBucket > getBucket (int id) const
void addBucket (const RCPtr< VBucket > &b)
HashTableStatVisitor removeBucket (int id)
Remove a vbucket by ID.
std::vector< int > getBuckets (void) const
size_t getSize (void) const
bool isBucketDeletion (int id)
void setBucketDeletion (int id, bool delBucket)
Constructor & Destructor Documentation
VBucketHolder::VBucketHolder (size_t sz) [inline]
References Atomic< T >::set().
VBucketHolder::VBucketHolder (const RCPtr< VBucketHolder > & vbh, size_t sz) [inline]
References Atomic< T >::set().
VBucketHolder::~VBucketHolder () [inline]
Member Function Documentation
void VBucketHolder::addBucket (const RCPtr< VBucket > & b) [inline]
References getLogger(), RCPtr< C >::reset(), and VBucket::toString().
RCPtr<VBucket> VBucketHolder::getBucket (int id) const [inline]
std::vector<int> VBucketHolder::getBuckets (void) const [inline]
size_t VBucketHolder::getSize (void) const [inline]
bool VBucketHolder::isBucketDeletion (int id) [inline]
References Atomic< T >::get().
HashTableStatVisitor VBucketHolder::removeBucket (int id) [inline]
Remove a vbucket by ID.
Returns:
the number of items removed
References RCPtr< C >::reset().
void VBucketHolder::setBucketDeletion (int id, bool delBucket) [inline]
References Atomic< T >::set().
The documentation for this class was generated from the following file:
vbucket.hh