membase core engine: EventuallyPersistentEngine Class Reference
EventuallyPersistentEngine Class Reference
#include <ep_engine.h>
Public Member Functions
ENGINE_ERROR_CODE initialize (const char *config)
void destroy ()
ENGINE_ERROR_CODE itemAllocate (const void *cookie, item **item, const void *key, const size_t nkey, const size_t nbytes, const int flags, const rel_time_t exptime)
ENGINE_ERROR_CODE itemDelete (const void *cookie, const void *key, const size_t nkey, uint64_t cas, uint16_t vbucket)
ENGINE_ERROR_CODE itemDelete (const void *cookie, const std::string &key, uint16_t vbucket)
void itemRelease (const void *cookie, item *item)
ENGINE_ERROR_CODE get (const void *cookie, item **item, const void *key, const int nkey, uint16_t vbucket)
ENGINE_ERROR_CODE getStats (const void *cookie, const char *stat_key, int nkey, ADD_STAT add_stat)
void resetStats ()
ENGINE_ERROR_CODE store (const void *cookie, item *itm, uint64_t *cas, ENGINE_STORE_OPERATION operation, uint16_t vbucket)
ENGINE_ERROR_CODE arithmetic (const void *cookie, const void *key, const int nkey, const bool increment, const bool create, const uint64_t delta, const uint64_t initial, const rel_time_t exptime, uint64_t *cas, uint64_t *result, uint16_t vbucket)
ENGINE_ERROR_CODE flush (const void *cookie, time_t when)
tap_event_t walkTapQueue (const void *cookie, item **itm, void **es, uint16_t *nes, uint8_t *ttl, uint16_t *flags, uint32_t *seqno, uint16_t *vbucket)
void createTapQueue (const void *cookie, std::string &client, uint32_t flags, const void *userdata, size_t nuserdata)
ENGINE_ERROR_CODE tapNotify (const void *cookie, void *engine_specific, uint16_t nengine, uint8_t ttl, uint16_t tap_flags, tap_event_t tap_event, uint32_t tap_seqno, const void *key, size_t nkey, uint32_t flags, uint32_t exptime, uint64_t cas, const void *data, size_t ndata, uint16_t vbucket)
void queueBackfill (TapConnection *tc, const void *tok)
Visit the objects and add them to the tap connecitons queue.
void handleDisconnect (const void *cookie)
protocol_binary_response_status stopFlusher (const char **msg)
protocol_binary_response_status startFlusher (const char **msg)
bool deleteVBucket (uint16_t vbid)
void setMinDataAge (int to)
void setQueueAgeCap (int to)
void setTxnSize (int to)
void setBGFetchDelay (uint32_t to)
protocol_binary_response_status evictKey (const std::string &key, uint16_t vbucket, const char **msg)
RCPtr< VBucket > getVBucket (uint16_t vbucket)
void setVBucketState (uint16_t vbid, vbucket_state_t to)
~EventuallyPersistentEngine ()
engine_info * getInfo ()
size_t getTapIdleTimeout () const
EPStats & getEpStats ()
template<typename V >
bool performTapOp (const std::string &name, TapOperation< V > &tapop, V arg)
EventuallyPersistentStore * getEpStore ()
size_t getItemExpiryWindow () const
SERVER_HANDLE_V1 * getServerApi ()
Friends
class LookupCallback
class BackFillVisitor
ENGINE_ERROR_CODE create_instance (uint64_t interface, GET_SERVER_API get_server_api, ENGINE_HANDLE **handle)
The only public interface to the eventually persistance engine.
void * EvpNotifyTapIo (void *arg)
Constructor & Destructor Documentation
EventuallyPersistentEngine::~EventuallyPersistentEngine () [inline]
Member Function Documentation
ENGINE_ERROR_CODE EventuallyPersistentEngine::arithmetic (const void * cookie, const void * key, const int nkey, const bool increment, const bool create, const uint64_t delta, const uint64_t initial, const rel_time_t exptime, uint64_t * cas, uint64_t * result, uint16_t vbucket) [inline]
References EPStats::arithCmdHisto, ep_abs_time, Item::getCas(), Item::getData(), Item::getFlags(), Item::getNBytes(), Item::setCas(), store(), and vals.
Referenced by EvpArithmetic().
void EventuallyPersistentEngine::createTapQueue (const void * cookie, std::string & client, uint32_t flags, const void * userdata, size_t nuserdata)
References getLogger(), and SyncObject::notify().
Referenced by EvpGetTapIterator().
bool EventuallyPersistentEngine::deleteVBucket (uint16_t vbid) [inline]
References EventuallyPersistentStore::deleteVBucket().
Referenced by deleteVBucket().
void EventuallyPersistentEngine::destroy ()
Referenced by EvpDestroy().
protocol_binary_response_status EventuallyPersistentEngine::evictKey (const std::string & key, uint16_t vbucket, const char ** msg) [inline]
References EventuallyPersistentStore::evictKey().
Referenced by evictKey().
ENGINE_ERROR_CODE EventuallyPersistentEngine::flush (const void * cookie, time_t when) [inline]
References EventuallyPersistentStore::reset().
Referenced by EvpFlush(), and tapNotify().
ENGINE_ERROR_CODE EventuallyPersistentEngine::get (const void * cookie, item ** item, const void * key, const int nkey, uint16_t vbucket) [inline]
References EventuallyPersistentStore::get(), and EPStats::getCmdHisto.
Referenced by EvpGet().
EPStats& EventuallyPersistentEngine::getEpStats () [inline]
Referenced by TapBGFetchCallback::callback(), EvpUnknownCommand(), and setFlushParam().
EventuallyPersistentStore* EventuallyPersistentEngine::getEpStore () [inline]
Referenced by TapBGFetchCallback::callback(), and TapConnection::completedBGFetchJob().
engine_info* EventuallyPersistentEngine::getInfo () [inline]
References info.
Referenced by EvpGetInfo().
size_t EventuallyPersistentEngine::getItemExpiryWindow () const [inline]
SERVER_HANDLE_V1* EventuallyPersistentEngine::getServerApi () [inline]
Referenced by TapBGFetchCallback::callback(), LookupCallback::callback(), EventuallyPersistentStore::completeBGFetch(), initialize(), and EventuallyPersistentStore::setVBucketState().
ENGINE_ERROR_CODE EventuallyPersistentEngine::getStats (const void * cookie, const char * stat_key, int nkey, ADD_STAT add_stat)
Referenced by EvpGetStats().
size_t EventuallyPersistentEngine::getTapIdleTimeout () const [inline]
RCPtr<VBucket> EventuallyPersistentEngine::getVBucket (uint16_t vbucket) [inline]
References EventuallyPersistentStore::getVBucket().
Referenced by deleteVBucket(), and getVbucket().
void EventuallyPersistentEngine::handleDisconnect (const void * cookie) [inline]
References getLogger(), and LockHolder::unlock().
Referenced by EvpHandleDisconnect().
ENGINE_ERROR_CODE EventuallyPersistentEngine::initialize (const char * config)
References ep_real_time(), EvpHandleDisconnect(), HashTable::getDefaultStorageValueType(), EventuallyPersistentStore::getDispatcher(), EventuallyPersistentStore::getFlusher(), getLogger(), StoredValue::getMaxDataSize(), getServerApi(), GetlExtension::initialize(), Priority::ItemPagerPriority, EPStats::mem_high_wat, EPStats::mem_low_wat, percentOf(), EventuallyPersistentStore::reset(), resetStats(), Dispatcher::schedule(), HashTable::setDefaultNumBuckets(), HashTable::setDefaultNumLocks(), HashTable::setDefaultStorageValueType(), StoredValue::setMaxDataSize(), setMinDataAge(), setQueueAgeCap(), small, Flusher::state(), and EPStats::warmOOM.
Referenced by EvpInitialize().
ENGINE_ERROR_CODE EventuallyPersistentEngine::itemAllocate (const void * cookie, item ** item, const void * key, const size_t nkey, const size_t nbytes, const int flags, const rel_time_t exptime) [inline]
References ep_abs_time.
Referenced by EvpItemAllocate().
ENGINE_ERROR_CODE EventuallyPersistentEngine::itemDelete (const void * cookie, const std::string & key, uint16_t vbucket) [inline]
References EventuallyPersistentStore::del().
ENGINE_ERROR_CODE EventuallyPersistentEngine::itemDelete (const void * cookie, const void * key, const size_t nkey, uint64_t cas, uint16_t vbucket) [inline]
Referenced by EvpItemDelete(), and tapNotify().
void EventuallyPersistentEngine::itemRelease (const void * cookie, item * item) [inline]
Referenced by EvpItemRelease(), and store().
template<typename V > bool EventuallyPersistentEngine::performTapOp (const std::string & name, TapOperation< V > & tapop, V arg) [inline]
References SyncObject::notify(), and TapOperation< V >::perform().
Referenced by BackFillVisitor::apply(), and TapBGFetchCallback::callback().
void EventuallyPersistentEngine::queueBackfill (TapConnection * tc, const void * tok)
Visit the objects and add them to the tap connecitons queue.
Todo:
this code should honor the backfill time!
References launch_backfill_thread().
void EventuallyPersistentEngine::resetStats () [inline]
References EPStats::reset().
Referenced by EvpResetStats(), and initialize().
void EventuallyPersistentEngine::setBGFetchDelay (uint32_t to) [inline]
References EventuallyPersistentStore::setBGFetchDelay().
Referenced by setFlushParam().
void EventuallyPersistentEngine::setMinDataAge (int to) [inline]
References EventuallyPersistentStore::setMinDataAge().
Referenced by initialize(), and setFlushParam().
void EventuallyPersistentEngine::setQueueAgeCap (int to) [inline]
References EventuallyPersistentStore::setQueueAgeCap().
Referenced by initialize(), and setFlushParam().
void EventuallyPersistentEngine::setTxnSize (int to) [inline]
References EventuallyPersistentStore::setTxnSize().
Referenced by setFlushParam().
void EventuallyPersistentEngine::setVBucketState (uint16_t vbid, vbucket_state_t to) [inline]
References EventuallyPersistentStore::setVBucketState().
Referenced by setVbucket().
protocol_binary_response_status EventuallyPersistentEngine::startFlusher (const char ** msg) [inline]
References EventuallyPersistentStore::getFlusher(), getLogger(), EventuallyPersistentStore::resumeFlusher(), and Flusher::stateName().
Referenced by startFlusher().
protocol_binary_response_status EventuallyPersistentEngine::stopFlusher (const char ** msg) [inline]
References EventuallyPersistentStore::getFlusher(), getLogger(), EventuallyPersistentStore::pauseFlusher(), and Flusher::stateName().
Referenced by stopFlusher().
ENGINE_ERROR_CODE EventuallyPersistentEngine::store (const void * cookie, item * itm, uint64_t * cas, ENGINE_STORE_OPERATION operation, uint16_t vbucket)
References EventuallyPersistentStore::add(), Item::append(), Item::getCas(), Item::getKey(), Item::getNKey(), itemRelease(), Item::prepend(), EventuallyPersistentStore::set(), Item::setVBucketId(), and EPStats::storeCmdHisto.
Referenced by arithmetic(), and EvpStore().
ENGINE_ERROR_CODE EventuallyPersistentEngine::tapNotify (const void * cookie, void * engine_specific, uint16_t nengine, uint8_t ttl, uint16_t tap_flags, tap_event_t tap_event, uint32_t tap_seqno, const void * key, size_t nkey, uint32_t flags, uint32_t exptime, uint64_t cas, const void * data, size_t ndata, uint16_t vbucket)
References flush(), itemDelete(), Blob::New(), EventuallyPersistentStore::set(), Item::setVBucketId(), EventuallyPersistentStore::setVBucketState(), EPStats::tapMutationHisto, and EPStats::tapVbucketSetHisto.
Referenced by EvpTapNotify().
tap_event_t EventuallyPersistentEngine::walkTapQueue (const void * cookie, item ** itm, void ** es, uint16_t * nes, uint8_t * ttl, uint16_t * flags, uint32_t * seqno, uint16_t * vbucket)
References EPStats::numTapFetched.
Referenced by EvpTapIterator().
Friends And Related Function Documentation
friend class BackFillVisitor [friend]
ENGINE_ERROR_CODE create_instance (uint64_t interface, GET_SERVER_API get_server_api, ENGINE_HANDLE ** handle) [friend]
The only public interface to the eventually persistance engine.
Allocate a new instance and initialize it
Parameters:
interface the highest interface the server supports (we only support interface 1)
get_server_api callback function to get the server exported API functions
handle Where to return the new instance
Returns:
ENGINE_SUCCESS on success
void* EvpNotifyTapIo (void * arg) [friend]
friend class LookupCallback [friend]
Member Data Documentation
char EventuallyPersistentEngine::buffer[sizeof(engine_info)+10 *sizeof(feature_info)]
engine_info EventuallyPersistentEngine::info
Referenced by getInfo().
The documentation for this class was generated from the following files:
ep_engine.h
ep_engine.cc