membase core engine: EventuallyPersistentStore Class Reference
EventuallyPersistentStore Class Reference
#include <ep.hh>
Public Member Functions
EventuallyPersistentStore (EventuallyPersistentEngine &theEngine, StrategicSqlite3 *t, bool startVb0)
~EventuallyPersistentStore ()
ENGINE_ERROR_CODE set (const Item &item, const void *cookie, bool force=false)
ENGINE_ERROR_CODE add (const Item &item, const void *cookie)
GetValue get (const std::string &key, uint16_t vbucket, const void *cookie, bool queueBG=true, bool honorStates=true)
Retrieve a value.
ENGINE_ERROR_CODE getFromUnderlying (const std::string &key, uint16_t vbucket, const void *cookie, shared_ptr< Callback< GetValue > > cb)
Retrieve an item from the disk for vkey stats.
protocol_binary_response_status evictKey (const std::string &key, uint16_t vbucket, const char **msg)
ENGINE_ERROR_CODE del (const std::string &key, uint16_t vbucket, const void *cookie)
void reset ()
void setMinDataAge (int to)
void setBGFetchDelay (uint32_t to)
Set the background fetch delay.
void setQueueAgeCap (int to)
void startDispatcher (void)
void startNonIODispatcher (void)
Dispatcher * getDispatcher (void)
Get the current dispatcher.
Dispatcher * getNonIODispatcher (void)
Get the current non-io dispatcher.
void stopFlusher (void)
void startFlusher (void)
bool pauseFlusher (void)
bool resumeFlusher (void)
void bgFetch (const std::string &key, uint16_t vbucket, uint64_t rowid, const void *cookie)
Enqueue a background fetch for a key.
void completeBGFetch (const std::string &key, uint16_t vbucket, uint64_t rowid, const void *cookie, hrtime_t init, hrtime_t start)
Complete a background fetch.
RCPtr< VBucket > getVBucket (uint16_t vbid)
void completeSetVBState (uint16_t vbid, const std::string &key)
void setVBucketState (uint16_t vbid, vbucket_state_t state)
void completeVBucketDeletion (uint16_t vbid)
bool deleteVBucket (uint16_t vbid)
void visit (VBucketVisitor &visitor)
void visitDepth (HashTableDepthVisitor &visitor)
size_t getHashSize ()
size_t getHashLocks ()
void warmup ()
int getTxnSize ()
void setTxnSize (int to)
const Flusher * getFlusher ()
bool getKeyStats (const std::string &key, uint16_t vbucket, key_stats &kstats)
bool getLocked (const std::string &key, uint16_t vbucket, Callback< GetValue > &cb, rel_time_t currentTime, uint32_t lockTimeout)
StrategicSqlite3 * getUnderlying ()
void deleteMany (std::list< std::pair< uint16_t, std::string > > &)
Friends
class Flusher
class BGFetchCallback
class VKeyStatBGFetchCallback
class TapConnection
class PersistenceCallback
class Deleter
Constructor & Destructor Documentation
EventuallyPersistentStore::EventuallyPersistentStore (EventuallyPersistentEngine & theEngine, StrategicSqlite3 * t, bool startVb0)
References VBucketMap::addBucket(), DEFAULT_TXN_SIZE, Flusher, EPStats::memOverhead, setTxnSize(), startDispatcher(), startFlusher(), and startNonIODispatcher().
EventuallyPersistentStore::~EventuallyPersistentStore ()
References Dispatcher::stop(), and stopFlusher().
Member Function Documentation
ENGINE_ERROR_CODE EventuallyPersistentStore::add (const Item & item, const void * cookie)
References ADD_EXISTS, ADD_NOMEM, ADD_SUCCESS, ADD_UNDEL, Item::getCas(), Item::getKey(), getVBucket(), Item::getVBucketId(), and EPStats::numNotMyVBuckets.
Referenced by EventuallyPersistentEngine::store().
void EventuallyPersistentStore::bgFetch (const std::string & key, uint16_t vbucket, uint64_t rowid, const void * cookie)
Enqueue a background fetch for a key.
Parameters:
the key to be bg fetched
vbucket the vbucket in which the key lives
cookie the cookie of the requestor
References BGFetchCallback, Priority::BgFetcherPriority, Atomic< T >::get(), getLogger(), and Dispatcher::schedule().
Referenced by get().
void EventuallyPersistentStore::completeBGFetch (const std::string & key, uint16_t vbucket, uint64_t rowid, const void * cookie, hrtime_t init, hrtime_t start)
Complete a background fetch.
Parameters:
key the key that was fetched
vbucket the vbucket in which the key lived
gv the result
References Histogram< T >::add(), EPStats::bg_fetched, EPStats::bgLoad, EPStats::bgLoadHisto, EPStats::bgMaxLoad, EPStats::bgMaxWait, EPStats::bgMinLoad, EPStats::bgMinWait, EPStats::bgNumOperations, EPStats::bgWait, EPStats::bgWaitHisto, RememberingCallback< T >::fired, StrategicSqlite3::get(), Atomic< T >::get(), gethrtime(), getLogger(), EventuallyPersistentEngine::getServerApi(), GetValue::getStatus(), Item::getValue(), GetValue::getValue(), getVBucket(), EPStats::numNonResident, Atomic< T >::setIfBigger(), Atomic< T >::setIfLess(), LockHolder::unlock(), RememberingCallback< T >::val, and RememberingCallback< T >::waitForValue().
Referenced by BGFetchCallback::callback().
void EventuallyPersistentStore::completeSetVBState (uint16_t vbid, const std::string & key)
References getLogger(), Dispatcher::schedule(), StrategicSqlite3::setVBState(), and Priority::SetVBucketPriority.
Referenced by SetVBStateCallback::callback().
void EventuallyPersistentStore::completeVBucketDeletion (uint16_t vbid)
References StrategicSqlite3::delVBucket(), EPStats::diskVBDelHisto, VBucketMap::getBucket(), getLogger(), VBucketMap::isBucketDeletion(), Dispatcher::schedule(), VBucketMap::setBucketDeletion(), LockHolder::unlock(), EPStats::vbucketDeletionFail, Priority::VBucketDeletionPriority, and EPStats::vbucketDeletions.
Referenced by VBucketDeletionCallback::callback().
ENGINE_ERROR_CODE EventuallyPersistentStore::del (const std::string & key, uint16_t vbucket, const void * cookie)
References getVBucket(), NOT_FOUND, EPStats::numNotMyVBuckets, queue_op_del, and WAS_CLEAN.
Referenced by EventuallyPersistentEngine::itemDelete().
void EventuallyPersistentStore::deleteMany (std::list< std::pair< uint16_t, std::string > > & keys)
References Deleter.
Referenced by ExpiredItemPager::callback(), and ItemPager::callback().
bool EventuallyPersistentStore::deleteVBucket (uint16_t vbid)
References EPStats::currentSize, Atomic< T >::decr(), Atomic< T >::get(), VBucketMap::getBucket(), EPStats::numNonResident, VBucketMap::removeBucket(), Dispatcher::schedule(), VBucketMap::setBucketDeletion(), EPStats::totalCacheSize, LockHolder::unlock(), and Priority::VBucketDeletionPriority.
Referenced by EventuallyPersistentEngine::deleteVBucket().
protocol_binary_response_status EventuallyPersistentStore::evictKey (const std::string & key, uint16_t vbucket, const char ** msg)
References getVBucket(), EPStats::numNonResident, and EPStats::numValueEjects.
Referenced by EventuallyPersistentEngine::evictKey().
GetValue EventuallyPersistentStore::get (const std::string & key, uint16_t vbucket, const void * cookie, bool queueBG = true, bool honorStates = true)
Retrieve a value.
Parameters:
key the key to fetch
vbucket the vbucket from which to retrieve the key
cookie the connection cookie
core the server API
queueBG if true, automatically queue a background fetch if necessary
honorStates if false, fetch a result regardless of state
Returns:
a GetValue representing the result of the request
References bgFetch(), ep_current_time, getVBucket(), and EPStats::numNotMyVBuckets.
Referenced by EventuallyPersistentEngine::get().
Dispatcher* EventuallyPersistentStore::getDispatcher (void) [inline]
Get the current dispatcher.
You can use this to queue io related jobs. Don't do stupid things with it.
Referenced by EventuallyPersistentEngine::initialize().
const Flusher * EventuallyPersistentStore::getFlusher ()
Referenced by EventuallyPersistentEngine::initialize(), EventuallyPersistentEngine::startFlusher(), and EventuallyPersistentEngine::stopFlusher().
ENGINE_ERROR_CODE EventuallyPersistentStore::getFromUnderlying (const std::string & key, uint16_t vbucket, const void * cookie, shared_ptr< Callback< GetValue > > cb)
Retrieve an item from the disk for vkey stats.
Parameters:
key the key to fetch
vbucket the vbucket from which to retrieve the key
cookie the connection cookie
cb callback to return an item fetched from the disk
Returns:
a status resulting form executing the method
References getVBucket(), EPStats::numNotMyVBuckets, Dispatcher::schedule(), VKeyStatBGFetchCallback, and Priority::VKeyStatBgFetcherPriority.
size_t EventuallyPersistentStore::getHashLocks () [inline]
References VBucketMap::getBucket().
size_t EventuallyPersistentStore::getHashSize () [inline]
References VBucketMap::getBucket().
bool EventuallyPersistentStore::getKeyStats (const std::string & key, uint16_t vbucket, key_stats & kstats)
References key_stats::cas, key_stats::data_age, key_stats::dirtied, key_stats::dirty, ep_abs_time, key_stats::exptime, key_stats::flags, getVBucket(), and key_stats::last_modification_time.
bool EventuallyPersistentStore::getLocked (const std::string & key, uint16_t vbucket, Callback< GetValue > & cb, rel_time_t currentTime, uint32_t lockTimeout)
References Callback< RV >::callback(), Item::getCas(), getVBucket(), EPStats::numNotMyVBuckets, and Item::setCas().
Referenced by GetlExtension::executeGetl().
Dispatcher* EventuallyPersistentStore::getNonIODispatcher (void) [inline]
Get the current non-io dispatcher.
Use this dispatcher to queue non-io jobs.
int EventuallyPersistentStore::getTxnSize () [inline]
References Atomic< T >::get().
StrategicSqlite3* EventuallyPersistentStore::getUnderlying () [inline]
Referenced by TapBGFetchCallback::callback(), and VKeyStatBGFetchCallback::callback().
RCPtr< VBucket > EventuallyPersistentStore::getVBucket (uint16_t vbid)
References VBucketMap::getBucket().
Referenced by add(), PersistenceCallback::callback(), completeBGFetch(), del(), evictKey(), get(), getFromUnderlying(), getKeyStats(), getLocked(), EventuallyPersistentEngine::getVBucket(), Deleter::operator()(), reset(), and set().
bool EventuallyPersistentStore::pauseFlusher (void)
References Flusher::pause().
Referenced by EventuallyPersistentEngine::stopFlusher().
void EventuallyPersistentStore::reset ()
References EPStats::currentSize, Atomic< T >::decr(), Atomic< T >::get(), VBucketMap::getBuckets(), getVBucket(), HashTableStatVisitor::memSize, HashTableStatVisitor::numNonResident, EPStats::numNonResident, queue_op_flush, and EPStats::totalCacheSize.
Referenced by EventuallyPersistentEngine::flush(), and EventuallyPersistentEngine::initialize().
bool EventuallyPersistentStore::resumeFlusher (void)
References Flusher::resume().
Referenced by EventuallyPersistentEngine::startFlusher().
ENGINE_ERROR_CODE EventuallyPersistentStore::set (const Item & item, const void * cookie, bool force = false)
References Item::getCas(), Item::getKey(), getVBucket(), Item::getVBucketId(), INVALID_CAS, INVALID_VBUCKET, IS_LOCKED, NOMEM, NOT_FOUND, EPStats::numNotMyVBuckets, WAS_CLEAN, and WAS_DIRTY.
Referenced by EventuallyPersistentEngine::store(), and EventuallyPersistentEngine::tapNotify().
void EventuallyPersistentStore::setBGFetchDelay (uint32_t to) [inline]
Set the background fetch delay.
This exists for debugging and testing purposes. It artificially injects delays into background fetches that are performed when the user requests an item whose value is not currently resident.
Parameters:
to how long to delay before performing a bg fetch
Referenced by EventuallyPersistentEngine::setBGFetchDelay().
void EventuallyPersistentStore::setMinDataAge (int to)
References EPStats::min_data_age, and Atomic< T >::set().
Referenced by EventuallyPersistentEngine::setMinDataAge().
void EventuallyPersistentStore::setQueueAgeCap (int to)
References EPStats::queue_age_cap, and Atomic< T >::set().
Referenced by EventuallyPersistentEngine::setQueueAgeCap().
void EventuallyPersistentStore::setTxnSize (int to) [inline]
References Atomic< T >::set().
Referenced by EventuallyPersistentStore(), and EventuallyPersistentEngine::setTxnSize().
void EventuallyPersistentStore::setVBucketState (uint16_t vbid, vbucket_state_t state)
References VBucketMap::addBucket(), VBucketMap::getBucket(), EventuallyPersistentEngine::getServerApi(), Priority::NotifyVBStateChangePriority, Dispatcher::schedule(), Priority::SetVBucketPriority, and VBucket::toString().
Referenced by EventuallyPersistentEngine::setVBucketState(), and EventuallyPersistentEngine::tapNotify().
void EventuallyPersistentStore::startDispatcher (void)
References Dispatcher::start().
Referenced by EventuallyPersistentStore().
void EventuallyPersistentStore::startFlusher (void)
References Flusher::start().
Referenced by EventuallyPersistentStore().
void EventuallyPersistentStore::startNonIODispatcher (void)
References Dispatcher::start().
Referenced by EventuallyPersistentStore().
void EventuallyPersistentStore::stopFlusher (void)
References Flusher::stop(), and Flusher::wait().
Referenced by ~EventuallyPersistentStore().
void EventuallyPersistentStore::visit (VBucketVisitor & visitor) [inline]
References VBucketMap::getBucket(), VBucketMap::getSize(), and VBucketVisitor::visitBucket().
Referenced by ExpiredItemPager::callback(), and ItemPager::callback().
void EventuallyPersistentStore::visitDepth (HashTableDepthVisitor & visitor) [inline]
References VBucketMap::getBucket().
void EventuallyPersistentStore::warmup () [inline]
References StrategicSqlite3::dump(), getLogger(), LoadStorageKVPairCallback::initVBucket(), and StrategicSqlite3::listPersistedVbuckets().
Friends And Related Function Documentation
friend class BGFetchCallback [friend]
Referenced by bgFetch().
friend class Deleter [friend]
Referenced by deleteMany().
friend class Flusher [friend]
Referenced by EventuallyPersistentStore().
friend class PersistenceCallback [friend]
friend class TapConnection [friend]
friend class VKeyStatBGFetchCallback [friend]
Referenced by getFromUnderlying().
The documentation for this class was generated from the following files:
ep.hh
ep.cc