membase core engine: StrategicSqlite3 Class Reference
StrategicSqlite3 Class Reference
#include <sqlite-kvstore.hh>
Public Member Functions
StrategicSqlite3 (EventuallyPersistentEngine &theEngine, SqliteStrategy *s)
Construct an instance of sqlite with the given database name.
~StrategicSqlite3 ()
Cleanup.
void reset ()
Reset database to a clean state.
void begin ()
Begin a transaction (if not already in one).
bool commit ()
Commit a transaction (unless not currently in one).
void rollback ()
Rollback a transaction (unless not currently in one).
void set (const Item &item, Callback< mutation_result > &cb)
Overrides set().
void get (const std::string &key, uint64_t rowid, Callback< GetValue > &cb)
Overrides get().
void del (const std::string &key, uint64_t rowid, Callback< int > &cb)
Overrides del().
bool delVBucket (uint16_t vbucket)
bool setVBState (uint16_t vbucket, const std::string &to)
std::map< uint16_t, std::string > listPersistedVbuckets (void)
void dump (Callback< GetValue > &cb)
Overrides dump.
Constructor & Destructor Documentation
StrategicSqlite3::StrategicSqlite3 (EventuallyPersistentEngine & theEngine, SqliteStrategy * s)
Construct an instance of sqlite with the given database name.
StrategicSqlite3::~StrategicSqlite3 () [inline]
Cleanup.
Member Function Documentation
void StrategicSqlite3::begin () [inline]
Begin a transaction (if not already in one).
bool StrategicSqlite3::commit () [inline]
Commit a transaction (unless not currently in one).
Returns false if the commit fails.
void StrategicSqlite3::del (const std::string & key, uint64_t rowid, Callback< int > & cb)
Overrides del().
References PreparedStatement::bind64(), Callback< RV >::callback(), Statements::del(), PreparedStatement::execute(), SqliteStrategy::forKey(), PreparedStatement::reset(), and EPStats::totalPersisted.
bool StrategicSqlite3::delVBucket (uint16_t vbucket)
References SqliteStrategy::allStatements(), PreparedStatement::bind(), PreparedStatement::execute(), SqliteStrategy::getDelVBucketStateST(), EPStats::io_num_write, and PreparedStatement::reset().
Referenced by EventuallyPersistentStore::completeVBucketDeletion().
void StrategicSqlite3::dump (Callback< GetValue > & cb)
Overrides dump.
References SqliteStrategy::allStatements(), PreparedStatement::bind(), Callback< RV >::callback(), PreparedStatement::column_blob(), PreparedStatement::column_bytes(), PreparedStatement::column_int(), PreparedStatement::column_int64(), ep_real_time(), PreparedStatement::fetch(), EPStats::io_num_read, EPStats::io_read_bytes, and PreparedStatement::reset().
Referenced by EventuallyPersistentStore::warmup().
void StrategicSqlite3::get (const std::string & key, uint64_t rowid, Callback< GetValue > & cb)
Overrides get().
References PreparedStatement::bind64(), Callback< RV >::callback(), PreparedStatement::column_blob(), PreparedStatement::column_bytes(), PreparedStatement::column_int(), PreparedStatement::column_int64(), PreparedStatement::fetch(), SqliteStrategy::forKey(), EPStats::io_num_read, EPStats::io_read_bytes, PreparedStatement::reset(), and Statements::sel().
Referenced by TapBGFetchCallback::callback(), VKeyStatBGFetchCallback::callback(), and EventuallyPersistentStore::completeBGFetch().
std::map< uint16_t, std::string > StrategicSqlite3::listPersistedVbuckets (void)
References PreparedStatement::column(), PreparedStatement::column_int(), PreparedStatement::fetch(), SqliteStrategy::getGetVBucketStateST(), EPStats::io_num_read, and PreparedStatement::reset().
Referenced by EventuallyPersistentStore::warmup().
void StrategicSqlite3::reset ()
Reset database to a clean state.
References SqliteStrategy::destroyTables(), and rollback().
void StrategicSqlite3::rollback () [inline]
Rollback a transaction (unless not currently in one).
Referenced by reset().
void StrategicSqlite3::set (const Item & item, Callback< mutation_result > & cb)
Overrides set().
References Item::getId().
bool StrategicSqlite3::setVBState (uint16_t vbucket, const std::string & to)
References PreparedStatement::bind(), PreparedStatement::execute(), SqliteStrategy::getSetVBucketStateST(), EPStats::io_num_write, and PreparedStatement::reset().
Referenced by EventuallyPersistentStore::completeSetVBState().
The documentation for this class was generated from the following files:
sqlite-kvstore.hh
sqlite-kvstore.cc