membase core engine: HistogramBin< T > Class Template Reference
HistogramBin< T > Class Template Reference
An individual bin of histogram data.
#include <histo.hh>
Public Member Functions
HistogramBin (T s, T e)
Get a HistogramBin covering [s, e).
T start () const
The starting value of this histogram bin (inclusive).
T end () const
The ending value of this histogram bin (exclusive).
size_t count () const
The count in this bin.
Friends
class Histogram< T >
Detailed Description
template<typename T>
class HistogramBin< T >
An individual bin of histogram data.
Constructor & Destructor Documentation
template<typename T> HistogramBin< T >::HistogramBin (T s, T e) [inline]
Get a HistogramBin covering [s, e).
Member Function Documentation
template<typename T> size_t HistogramBin< T >::count () const [inline]
The count in this bin.
References Atomic< T >::get().
Referenced by HistogramBinSampleAdder< T >::operator()(), and histo_stat_adder< T >::operator()().
template<typename T> T HistogramBin< T >::end () const [inline]
The ending value of this histogram bin (exclusive).
Referenced by histo_stat_adder< T >::operator()().
template<typename T> T HistogramBin< T >::start (void) const [inline]
The starting value of this histogram bin (inclusive).
Referenced by histo_stat_adder< T >::operator()().
Friends And Related Function Documentation
template<typename T> friend class Histogram< T > [friend]
The documentation for this class was generated from the following file:
histo.hh