membase core engine: TapConnection Class Reference
TapConnection Class Reference
Class used by the EventuallyPersistentEngine to keep track of all information needed per Tap connection.
#include <tapconnection.hh>
Public Member Functions
void completeBackfill ()
void gotBGItem (Item *item)
Invoked each time a background item fetch completes.
void completedBGFetchJob ()
Invoked once per batch bg fetch job.
const std::string & getName () const
Friends
class EventuallyPersistentEngine
class BackFillVisitor
class TapBGFetchCallback
Detailed Description
Class used by the EventuallyPersistentEngine to keep track of all information needed per Tap connection.
Member Function Documentation
void TapConnection::completeBackfill () [inline]
Referenced by CompleteBackfillTapOperation::perform().
void TapConnection::completedBGFetchJob ()
Invoked once per batch bg fetch job.
References EventuallyPersistentEngine::getEpStore().
Referenced by CompletedBGFetchTapOperation::perform().
const std::string& TapConnection::getName () const [inline]
Referenced by addTapStat().
void TapConnection::gotBGItem (Item * item)
Invoked each time a background item fetch completes.
Referenced by ReceivedItemTapOperation::perform().
Friends And Related Function Documentation
friend class BackFillVisitor [friend]
friend class EventuallyPersistentEngine [friend]
friend class TapBGFetchCallback [friend]
The documentation for this class was generated from the following files:
tapconnection.hh
ep_engine.cc
tapconnection.cc