membase core engine: LockHolder Class Reference
LockHolder Class Reference
RAII lock holder to guarantee release of the lock.
#include <locks.hh>
Public Member Functions
LockHolder (Mutex &m)
Acquire the lock in the given mutex.
~LockHolder ()
Release the lock.
void lock ()
Relock a lock that was manually unlocked.
void unlock ()
Manually unlock a lock.
Detailed Description
RAII lock holder to guarantee release of the lock.
It is a very bad idea to unlock a lock held by a LockHolder without using the LockHolder::unlock method.
Constructor & Destructor Documentation
LockHolder::LockHolder (Mutex & m) [inline]
Acquire the lock in the given mutex.
References lock().
LockHolder::~LockHolder () [inline]
Release the lock.
References unlock().
Member Function Documentation
void LockHolder::lock () [inline]
Relock a lock that was manually unlocked.
References Mutex::acquire().
Referenced by LockHolder().
void LockHolder::unlock () [inline]
Manually unlock a lock.
References Mutex::release().
Referenced by EventuallyPersistentStore::completeBGFetch(), EventuallyPersistentStore::completeVBucketDeletion(), EventuallyPersistentStore::deleteVBucket(), EventuallyPersistentEngine::handleDisconnect(), Dispatcher::run(), Dispatcher::stop(), HashTable::visit(), and ~LockHolder().
The documentation for this class was generated from the following file:
locks.hh