membase core engine: SqliteStrategy Class Reference
SqliteStrategy Class Reference
#include <sqlite-strategies.hh>
Public Member Functions
SqliteStrategy (EventuallyPersistentEngine &theEngine, const char *const fn, const char *const finit=NULL, const char *const pfinit=NULL)
virtual ~SqliteStrategy ()
const std::vector< Statements * > & allStatements ()
Statements * forKey (const std::string &key)
PreparedStatement * getSetVBucketStateST ()
PreparedStatement * getDelVBucketStateST ()
PreparedStatement * getGetVBucketStateST ()
virtual void initMetaTables ()
virtual void initTables (void)
virtual void initStatements (void)
virtual void destroyTables (void)
void destroyStatements (void)
virtual void initMetaStatements (void)
virtual void destroyMetaStatements (void)
void execute (const char *const query)
sqlite3 * open (void)
void close (void)
Protected Member Functions
void doFile (const char *const filename)
Protected Attributes
EventuallyPersistentEngine & engine
const char *const filename
const char *const initFile
const char *const postInitFile
sqlite3 * db
std::vector< Statements * > statements
PreparedStatement * set_vb_stmt
PreparedStatement * del_vb_stmt
PreparedStatement * sel_vb_stmt
Constructor & Destructor Documentation
SqliteStrategy::SqliteStrategy (EventuallyPersistentEngine & theEngine, const char *const fn, const char *const finit = NULL, const char *const pfinit = NULL) [inline]
virtual SqliteStrategy::~SqliteStrategy () [inline, virtual]
References close().
Member Function Documentation
const std::vector<Statements *>& SqliteStrategy::allStatements () [inline]
References statements.
Referenced by StrategicSqlite3::delVBucket(), and StrategicSqlite3::dump().
void SqliteStrategy::close (void)
References db, and destroyStatements().
Referenced by ~SqliteStrategy().
void SqliteStrategy::destroyMetaStatements (void) [virtual]
References del_vb_stmt, sel_vb_stmt, and set_vb_stmt.
Referenced by destroyStatements().
void SqliteStrategy::destroyStatements (void)
References destroyMetaStatements(), and statements.
Referenced by close().
void SqliteStrategy::destroyTables (void) [virtual]
Reimplemented in MultiDBSqliteStrategy.
References execute().
Referenced by StrategicSqlite3::reset().
void SqliteStrategy::doFile (const char *const filename) [protected]
References db, SqliteEvaluator::eval(), and getLogger().
Referenced by open().
void SqliteStrategy::execute (const char *const query)
References db, and PreparedStatement::execute().
Referenced by MultiDBSqliteStrategy::destroyTables(), destroyTables(), initMetaTables(), MultiDBSqliteStrategy::initTables(), and initTables().
Statements* SqliteStrategy::forKey (const std::string & key) [inline]
References statements.
Referenced by StrategicSqlite3::del(), and StrategicSqlite3::get().
PreparedStatement* SqliteStrategy::getDelVBucketStateST () [inline]
References del_vb_stmt.
Referenced by StrategicSqlite3::delVBucket().
PreparedStatement* SqliteStrategy::getGetVBucketStateST () [inline]
References sel_vb_stmt.
Referenced by StrategicSqlite3::listPersistedVbuckets().
PreparedStatement* SqliteStrategy::getSetVBucketStateST () [inline]
References set_vb_stmt.
Referenced by StrategicSqlite3::setVBState().
void SqliteStrategy::initMetaStatements (void) [virtual]
References db, del_vb_stmt, sel_vb_stmt, and set_vb_stmt.
Referenced by MultiDBSqliteStrategy::initStatements(), and initStatements().
void SqliteStrategy::initMetaTables () [virtual]
References db, and execute().
Referenced by open().
void SqliteStrategy::initStatements (void) [virtual]
Reimplemented in MultiDBSqliteStrategy.
References db, initMetaStatements(), and statements.
Referenced by open().
void SqliteStrategy::initTables (void) [virtual]
Reimplemented in MultiDBSqliteStrategy.
References db, and execute().
Referenced by open().
sqlite3 * SqliteStrategy::open (void)
References db, doFile(), filename, initFile, initMetaTables(), initStatements(), initTables(), and postInitFile.
Member Data Documentation
sqlite3* SqliteStrategy::db [protected]
Referenced by close(), doFile(), execute(), initMetaStatements(), initMetaTables(), MultiDBSqliteStrategy::initStatements(), initStatements(), initTables(), and open().
PreparedStatement* SqliteStrategy::del_vb_stmt [protected]
Referenced by destroyMetaStatements(), getDelVBucketStateST(), and initMetaStatements().
EventuallyPersistentEngine& SqliteStrategy::engine [protected]
const char* const SqliteStrategy::filename [protected]
Referenced by MultiDBSqliteStrategy::initTables(), and open().
const char* const SqliteStrategy::initFile [protected]
Referenced by open().
const char* const SqliteStrategy::postInitFile [protected]
Referenced by open().
PreparedStatement* SqliteStrategy::sel_vb_stmt [protected]
Referenced by destroyMetaStatements(), getGetVBucketStateST(), and initMetaStatements().
PreparedStatement* SqliteStrategy::set_vb_stmt [protected]
Referenced by destroyMetaStatements(), getSetVBucketStateST(), and initMetaStatements().
std::vector<Statements *> SqliteStrategy::statements [protected]
Referenced by allStatements(), destroyStatements(), forKey(), MultiDBSqliteStrategy::initStatements(), and initStatements().
The documentation for this class was generated from the following files:
sqlite-strategies.hh
sqlite-strategies.cc