membase core engine: GetValue Class Reference
GetValue Class Reference
Value for callback for GET operations.
#include <callbacks.hh>
Public Member Functions
GetValue ()
GetValue (Item *v, ENGINE_ERROR_CODE s=ENGINE_SUCCESS, uint64_t i=-1)
Item * getValue ()
The value retrieved for the key.
ENGINE_ERROR_CODE getStatus () const
Engine code describing what happened.
uint64_t getId ()
Get the item's underlying ID (if applicable).
Detailed Description
Value for callback for GET operations.
Constructor & Destructor Documentation
GetValue::GetValue () [inline]
GetValue::GetValue (Item * v, ENGINE_ERROR_CODE s = ENGINE_SUCCESS, uint64_t i = -1) [inline, explicit]
Member Function Documentation
uint64_t GetValue::getId () [inline]
Get the item's underlying ID (if applicable).
ENGINE_ERROR_CODE GetValue::getStatus () const [inline]
Engine code describing what happened.
Referenced by TapBGFetchCallback::callback(), LookupCallback::callback(), EventuallyPersistentStore::completeBGFetch(), and GetlExtension::executeGetl().
Item* GetValue::getValue () [inline]
The value retrieved for the key.
Referenced by TapBGFetchCallback::callback(), LookupCallback::callback(), LoadStorageKVPairCallback::callback(), EventuallyPersistentStore::completeBGFetch(), and GetlExtension::executeGetl().
The documentation for this class was generated from the following file:
callbacks.hh