membase core engine: LoadStorageKVPairCallback Class Reference
LoadStorageKVPairCallback Class Reference
Helper class used to insert items into the storage by using the KVStore::dump method to load items from the database.
#include <ep.hh>
Public Member Functions
LoadStorageKVPairCallback (VBucketMap &vb, EPStats &st)
void initVBucket (uint16_t vbid, vbucket_state_t state=pending)
void callback (GetValue &val)
Method called on callback.
Detailed Description
Helper class used to insert items into the storage by using the KVStore::dump method to load items from the database.
Constructor & Destructor Documentation
LoadStorageKVPairCallback::LoadStorageKVPairCallback (VBucketMap & vb, EPStats & st) [inline]
Member Function Documentation
void LoadStorageKVPairCallback::callback (GetValue & value) [virtual]
Method called on callback.
Implements Callback< GetValue >.
References ADD_EXISTS, ADD_NOMEM, ADD_SUCCESS, ADD_UNDEL, VBucketMap::addBucket(), VBucketMap::getBucket(), Item::getKey(), getLogger(), GetValue::getValue(), Item::getVBucketId(), EPStats::numNonResident, EPStats::numValueEjects, RCPtr< C >::reset(), EPStats::warmDups, EPStats::warmedUp, and EPStats::warmOOM.
void LoadStorageKVPairCallback::initVBucket (uint16_t vbid, vbucket_state_t state = pending)
References VBucketMap::addBucket(), VBucketMap::getBucket(), and RCPtr< C >::reset().
Referenced by EventuallyPersistentStore::warmup().
The documentation for this class was generated from the following files:
ep.hh
ep.cc