membase core engine: PersistenceCallback Class Reference
PersistenceCallback Class Reference
Public Member Functions
PersistenceCallback (const QueuedItem &qi, std::queue< QueuedItem > *q, EventuallyPersistentStore *st, rel_time_t qd, rel_time_t d, EPStats *s)
void callback (mutation_result &value)
void callback (int &value)
Method called on callback.
Constructor & Destructor Documentation
PersistenceCallback::PersistenceCallback (const QueuedItem & qi, std::queue< QueuedItem > * q, EventuallyPersistentStore * st, rel_time_t qd, rel_time_t d, EPStats * s) [inline]
Member Function Documentation
void PersistenceCallback::callback (mutation_result & value) [inline]
References StoredValue::ejectValue(), StoredValue::getCurrentSize(), QueuedItem::getKey(), EventuallyPersistentStore::getVBucket(), QueuedItem::getVBucketId(), EPStats::mem_low_wat, and EPStats::newItems.
void PersistenceCallback::callback (int & value) [inline, virtual]
Method called on callback.
Implements Callback< int >.
References EPStats::delItems, QueuedItem::getKey(), EventuallyPersistentStore::getVBucket(), and QueuedItem::getVBucketId().
The documentation for this class was generated from the following file:
ep.cc