membase core engine: Mutex Class Reference
Mutex Class Reference
Abstraction built on top of pthread mutexes.
#include <mutex.hh>
Public Member Functions
Mutex ()
virtual ~Mutex ()
Protected Member Functions
void acquire ()
void release ()
void setHolder ()
Mutex (const Mutex &)
void operator= (const Mutex &)
Protected Attributes
pthread_mutex_t mutex
pthread_t holder
Friends
class LockHolder
class MultiLockHolder
Detailed Description
Abstraction built on top of pthread mutexes.
Constructor & Destructor Documentation
Mutex::Mutex () [inline]
References mutex.
virtual Mutex::~Mutex () [inline, virtual]
References mutex.
Mutex::Mutex (const Mutex &) [protected]
Member Function Documentation
void Mutex::acquire () [inline, protected]
References mutex, and setHolder().
Referenced by MultiLockHolder::lock(), and LockHolder::lock().
void Mutex::operator= (const Mutex &) [protected]
void Mutex::release () [inline, protected]
References holder, and mutex.
Referenced by MultiLockHolder::unlock(), and LockHolder::unlock().
void Mutex::setHolder () [inline, protected]
References holder.
Referenced by acquire(), and SyncObject::wait().
Friends And Related Function Documentation
friend class LockHolder [friend]
friend class MultiLockHolder [friend]
Member Data Documentation
pthread_t Mutex::holder [protected]
Referenced by release(), and setHolder().
pthread_mutex_t Mutex::mutex [protected]
Referenced by acquire(), Mutex(), release(), SyncObject::wait(), and ~Mutex().
The documentation for this class was generated from the following file:
mutex.hh