membase core engine: LookupCallback Class Reference
LookupCallback Class Reference
#include <ep_engine.h>
Public Member Functions
LookupCallback (EventuallyPersistentEngine *e, const void *c)
virtual void callback (GetValue &value)
Method called on callback.
Constructor & Destructor Documentation
LookupCallback::LookupCallback (EventuallyPersistentEngine * e, const void * c) [inline]
Member Function Documentation
void LookupCallback::callback (GetValue & value) [virtual]
Method called on callback.
Implements Callback< GetValue >.
References EventuallyPersistentEngine::getServerApi(), GetValue::getStatus(), and GetValue::getValue().
The documentation for this class was generated from the following files:
ep_engine.h
ep_engine.cc