membase core engine: VBucketFilter Class Reference
VBucketFilter Class Reference
Function object that returns true if the given vbucket is acceptable.
#include <vbucket.hh>
Public Member Functions
VBucketFilter ()
Instiatiate a VBucketFilter that always returns true.
VBucketFilter (std::vector< uint16_t > a)
Instantiate a VBucketFilter that returns true for any of the given vbucket IDs.
bool operator() (uint16_t v) const
size_t size () const
bool empty () const
VBucketFilter filter_diff (const VBucketFilter &other) const
Calculate the difference between this and another filter.
VBucketFilter filter_intersection (const VBucketFilter &other) const
Calculate the intersection between this and another filter.
const std::vector< uint16_t > & getVector () const
Friends
std::ostream & operator<< (std::ostream &out, const VBucketFilter &filter)
Dump the filter in a human readable form ("{ bucket, bucket, bucket }" to the specified output stream.
Detailed Description
Function object that returns true if the given vbucket is acceptable.
Constructor & Destructor Documentation
VBucketFilter::VBucketFilter () [inline, explicit]
Instiatiate a VBucketFilter that always returns true.
Referenced by filter_diff(), and filter_intersection().
VBucketFilter::VBucketFilter (std::vector< uint16_t > a) [inline, explicit]
Instantiate a VBucketFilter that returns true for any of the given vbucket IDs.
Member Function Documentation
bool VBucketFilter::empty () const [inline]
VBucketFilter VBucketFilter::filter_diff (const VBucketFilter & other) const
Calculate the difference between this and another filter.
If "this" contains elements, [1,2,3,4] and other contains [3,4,5,6] the returned filter contains: [1,2,5,6]
Parameters:
other the other filter to compare with
Returns:
a new filter with the elements present in only one of the two filters.
References size(), and VBucketFilter().
VBucketFilter VBucketFilter::filter_intersection (const VBucketFilter & other) const
Calculate the intersection between this and another filter.
If "this" contains elements, [1,2,3,4] and other contains [3,4,5,6] the returned filter contains: [3,4]
Parameters:
other the other filter to compare with
Returns:
a new filter with the elements present in both of the two filters.
References size(), and VBucketFilter().
const std::vector<uint16_t>& VBucketFilter::getVector () const [inline]
bool VBucketFilter::operator() (uint16_t v) const [inline]
size_t VBucketFilter::size () const [inline]
Referenced by filter_diff(), and filter_intersection().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const VBucketFilter & filter) [friend]
Dump the filter in a human readable form ("{ bucket, bucket, bucket }" to the specified output stream.
The documentation for this class was generated from the following files:
vbucket.hh
vbucket.cc