membase core engine: PreparedStatement Class Reference
PreparedStatement Class Reference
A sqlite prepared statement.
#include <sqlite-pst.hh>
Public Member Functions
PreparedStatement (sqlite3 *d, const char *query)
Construct a prepared statement.
~PreparedStatement ()
Clean up.
void bind (int pos, const char *s)
Bind a null-terminated string parameter to a binding in this statement.
void bind (int pos, const char *s, size_t nbytes)
Bind a string parameter to a binding in this statement.
void bind (int pos, int d)
Bind a uint32 value.
void bind64 (int pos, uint64_t d)
Bind a uint64 value.
int execute ()
Execute a prepared statement that does not return results.
bool fetch ()
Execute a prepared statement that does return results and/or return the next row.
void reset ()
Reset the bindings.
const char * column (int x)
Get the value at a given column in the current row.
const void * column_blob (int x)
Get the value as a blob from the given column in the current row.
int column_bytes (int x)
Get the number of bytes stored in the given column for the current row.
int column_int (int x)
Get the integer valueof the given column at the current row.
uint64_t column_int64 (int x)
Get the 64-bit integer value of the given column at the current row.
Detailed Description
A sqlite prepared statement.
Constructor & Destructor Documentation
PreparedStatement::PreparedStatement (sqlite3 * d, const char * query)
Construct a prepared statement.
Parameters:
d the DB where the prepared statement will execute
query the query to prepare
PreparedStatement::~PreparedStatement ()
Clean up.
Member Function Documentation
void PreparedStatement::bind (int pos, const char * s)
Bind a null-terminated string parameter to a binding in this statement.
Parameters:
pos the binding position (starting at 1)
s the value to bind
Referenced by StrategicSqlite3::delVBucket(), StrategicSqlite3::dump(), and StrategicSqlite3::setVBState().
void PreparedStatement::bind (int pos, const char * s, size_t nbytes)
Bind a string parameter to a binding in this statement.
Parameters:
pos the binding position (starting at 1)
s the value to bind
nbytes number of bytes in the string.
void PreparedStatement::bind (int pos, int d)
Bind a uint32 value.
Parameters:
pos the binding position (starting at 1)
d the value to bind
void PreparedStatement::bind64 (int pos, uint64_t d)
Bind a uint64 value.
Parameters:
pos the binding position (starting at 1)
d the value to bind
Referenced by StrategicSqlite3::del(), and StrategicSqlite3::get().
const char * PreparedStatement::column (int x)
Get the value at a given column in the current row.
Use this along with fetch.
Parameters:
x the column number
Returns:
the value
Referenced by StrategicSqlite3::listPersistedVbuckets().
const void * PreparedStatement::column_blob (int x)
Get the value as a blob from the given column in the current row.
Use this along with fetch and column_bytes().
Parameters:
x the column number
Returns:
the value
Referenced by StrategicSqlite3::dump(), and StrategicSqlite3::get().
int PreparedStatement::column_bytes (int x)
Get the number of bytes stored in the given column for the current row.
Use this along with fetch and column() or column_blob().
Parameters:
x the column number
Returns:
the number of bytes found
Referenced by StrategicSqlite3::dump(), and StrategicSqlite3::get().
int PreparedStatement::column_int (int x)
Get the integer valueof the given column at the current row.
Use this along with fetch.
Parameters:
x the column number
Returns:
the value
Referenced by StrategicSqlite3::dump(), StrategicSqlite3::get(), and StrategicSqlite3::listPersistedVbuckets().
uint64_t PreparedStatement::column_int64 (int x)
Get the 64-bit integer value of the given column at the current row.
Use this along with fetch.
Parameters:
x the column number
Returns:
the value
Referenced by StrategicSqlite3::dump(), and StrategicSqlite3::get().
int PreparedStatement::execute ()
Execute a prepared statement that does not return results.
Returns:
how many rows were affected
References MAX_STEPS.
Referenced by StrategicSqlite3::del(), StrategicSqlite3::delVBucket(), SqliteStrategy::execute(), and StrategicSqlite3::setVBState().
bool PreparedStatement::fetch ()
Execute a prepared statement that does return results and/or return the next row.
Returns:
true if there are more rows after this one
Referenced by StrategicSqlite3::dump(), StrategicSqlite3::get(), and StrategicSqlite3::listPersistedVbuckets().
void PreparedStatement::reset ()
Reset the bindings.
Call this before reusing a prepared statement.
Referenced by StrategicSqlite3::del(), StrategicSqlite3::delVBucket(), StrategicSqlite3::dump(), StrategicSqlite3::get(), StrategicSqlite3::listPersistedVbuckets(), and StrategicSqlite3::setVBState().
The documentation for this class was generated from the following files:
sqlite-pst.hh
sqlite-pst.cc