membase core engine: Item Class Reference
Item Class Reference
The Item structure we use to pass information between the memcached core and the backend.
#include <item.hh>
Public Member Functions
Item (const void *k, const size_t nk, const size_t nb, const int fl, const time_t exp, uint64_t theCas=0, int64_t i=-1, uint16_t vbid=0)
Item (const std::string &k, const int fl, const time_t exp, const void *dta, const size_t nb, uint64_t theCas=0, int64_t i=-1, uint16_t vbid=0)
Item (const std::string &k, const int fl, const time_t exp, value_t val, uint64_t theCas=0, int64_t i=-1, uint16_t vbid=0)
Item (const void *k, uint16_t nk, const int fl, const time_t exp, const void *dta, const size_t nb, uint64_t theCas=0, int64_t i=-1, uint16_t vbid=0)
~Item ()
const char * getData () const
value_t getValue () const
const std::string & getKey () const
int64_t getId () const
int getNKey () const
uint32_t getNBytes () const
time_t getExptime () const
int getFlags () const
uint64_t getCas () const
void setCas ()
void setCas (uint64_t ncas)
bool append (const Item &item)
Append another item to this item.
bool prepend (const Item &item)
Prepend another item to this item.
uint16_t getVBucketId (void) const
void setVBucketId (uint16_t to)
bool isExpired (time_t asOf) const
Check if this item is expired or not.
Detailed Description
The Item structure we use to pass information between the memcached core and the backend.
Please note that the kvstore don't store these objects, so we do have an extra layer of memory copying :(
Constructor & Destructor Documentation
Item::Item (const void * k, const size_t nk, const size_t nb, const int fl, const time_t exp, uint64_t theCas = 0, int64_t i = -1, uint16_t vbid = 0) [inline]
Item::Item (const std::string & k, const int fl, const time_t exp, const void * dta, const size_t nb, uint64_t theCas = 0, int64_t i = -1, uint16_t vbid = 0) [inline]
Item::Item (const std::string & k, const int fl, const time_t exp, value_t val, uint64_t theCas = 0, int64_t i = -1, uint16_t vbid = 0) [inline]
Item::Item (const void * k, uint16_t nk, const int fl, const time_t exp, const void * dta, const size_t nb, uint64_t theCas = 0, int64_t i = -1, uint16_t vbid = 0) [inline]
Item::~Item () [inline]
Member Function Documentation
bool Item::append (const Item & item)
Append another item to this item.
Parameters:
item the item to append to this one
Returns:
true if success
References getValue(), and Blob::New().
Referenced by EventuallyPersistentEngine::store().
uint64_t Item::getCas () const [inline]
Referenced by HashTable::add(), EventuallyPersistentStore::add(), EventuallyPersistentEngine::arithmetic(), EvpGetItemInfo(), GetlExtension::executeGetl(), EventuallyPersistentStore::getLocked(), EventuallyPersistentStore::set(), and EventuallyPersistentEngine::store().
const char* Item::getData () const [inline]
Referenced by EventuallyPersistentEngine::arithmetic(), EvpGetItemInfo(), and GetlExtension::executeGetl().
time_t Item::getExptime () const [inline]
Referenced by HashTable::add(), EvpGetItemInfo(), and isExpired().
int Item::getFlags () const [inline]
Referenced by HashTable::add(), EventuallyPersistentEngine::arithmetic(), EvpGetItemInfo(), and GetlExtension::executeGetl().
int64_t Item::getId () const [inline]
Referenced by StrategicSqlite3::set().
const std::string& Item::getKey (void) const [inline]
Referenced by HashTable::add(), EventuallyPersistentStore::add(), LoadStorageKVPairCallback::callback(), EvpGetItemInfo(), GetlExtension::executeGetl(), EventuallyPersistentStore::set(), and EventuallyPersistentEngine::store().
uint32_t Item::getNBytes () const [inline]
Referenced by EventuallyPersistentEngine::arithmetic(), EvpGetItemInfo(), and GetlExtension::executeGetl().
int Item::getNKey () const [inline]
Referenced by EvpGetItemInfo(), and EventuallyPersistentEngine::store().
value_t Item::getValue () const [inline]
Referenced by HashTable::add(), append(), EventuallyPersistentStore::completeBGFetch(), and prepend().
uint16_t Item::getVBucketId (void) const [inline]
Referenced by EventuallyPersistentStore::add(), LoadStorageKVPairCallback::callback(), and EventuallyPersistentStore::set().
bool Item::isExpired (time_t asOf) const [inline]
Check if this item is expired or not.
Parameters:
asOf the time to be compared with this item's expiry time
Returns:
true if this item's expiry time < asOf
References getExptime().
bool Item::prepend (const Item & item)
Prepend another item to this item.
Parameters:
item the item to prepend to this one
Returns:
true if success
References getValue(), and Blob::New().
Referenced by EventuallyPersistentEngine::store().
void Item::setCas (uint64_t ncas) [inline]
void Item::setCas () [inline]
Referenced by HashTable::add(), EventuallyPersistentEngine::arithmetic(), and EventuallyPersistentStore::getLocked().
void Item::setVBucketId (uint16_t to) [inline]
Referenced by EventuallyPersistentEngine::store(), and EventuallyPersistentEngine::tapNotify().
The documentation for this class was generated from the following files:
item.hh
item.cc