membase core engine: TapBGFetchCallback Class Reference
TapBGFetchCallback Class Reference
Public Member Functions
TapBGFetchCallback (EventuallyPersistentEngine *e, const std::string &n, const std::string &k, uint64_t r, const void *c)
bool callback (Dispatcher &d, TaskId t)
Perform my task.
std::string description ()
Print a human-readable description of this callback.
Constructor & Destructor Documentation
TapBGFetchCallback::TapBGFetchCallback (EventuallyPersistentEngine * e, const std::string & n, const std::string & k, uint64_t r, const void * c) [inline]
Member Function Documentation
bool TapBGFetchCallback::callback (Dispatcher & d, TaskId t) [inline, virtual]
Perform my task.
Parameters:
d the dispatcher running this task
t the task
Returns:
true if the task should run again
Implements DispatcherCallback.
References Histogram< T >::add(), RememberingCallback< T >::fired, StrategicSqlite3::get(), EventuallyPersistentEngine::getEpStats(), EventuallyPersistentEngine::getEpStore(), gethrtime(), EventuallyPersistentEngine::getServerApi(), GetValue::getStatus(), EventuallyPersistentStore::getUnderlying(), GetValue::getValue(), EventuallyPersistentEngine::performTapOp(), Atomic< T >::setIfBigger(), Atomic< T >::setIfLess(), EPStats::tapBgLoad, EPStats::tapBgLoadHisto, EPStats::tapBgMaxLoad, EPStats::tapBgMaxWait, EPStats::tapBgMinLoad, EPStats::tapBgMinWait, EPStats::tapBgNumOperations, EPStats::tapBgWait, EPStats::tapBgWaitHisto, RememberingCallback< T >::val, and RememberingCallback< T >::waitForValue().
std::string TapBGFetchCallback::description () [inline, virtual]
Print a human-readable description of this callback.
Implements DispatcherCallback.
The documentation for this class was generated from the following file:
tapconnection.cc