membase core engine: ItemPager Class Reference
ItemPager Class Reference
Dispatcher job responsible for periodically pushing data out of memory.
#include <item_pager.hh>
Public Member Functions
ItemPager (EventuallyPersistentStore *s, EPStats &st)
Construct an ItemPager.
bool callback (Dispatcher &d, TaskId t)
Perform my task.
std::string description ()
Print a human-readable description of this callback.
Detailed Description
Dispatcher job responsible for periodically pushing data out of memory.
Constructor & Destructor Documentation
ItemPager::ItemPager (EventuallyPersistentStore * s, EPStats & st) [inline]
Construct an ItemPager.
Parameters:
s the store (where we'll visit)
st the stats
Member Function Documentation
bool ItemPager::callback (Dispatcher & d, TaskId t) [virtual]
Perform my task.
Parameters:
d the dispatcher running this task
t the task
Returns:
true if the task should run again
Implements DispatcherCallback.
References EventuallyPersistentStore::deleteMany(), PagingVisitor::expired, EPStats::expired, StoredValue::getCurrentSize(), getLogger(), Atomic< T >::incr(), EPStats::mem_high_wat, EPStats::mem_low_wat, PagingVisitor::numEjected(), PagingVisitor::numFailedEjects(), EPStats::numFailedEjects, EPStats::numNonResident, EPStats::numValueEjects, EPStats::pagerRuns, Dispatcher::snooze(), and EventuallyPersistentStore::visit().
std::string ItemPager::description () [inline, virtual]
Print a human-readable description of this callback.
Implements DispatcherCallback.
The documentation for this class was generated from the following files:
item_pager.hh
item_pager.cc