membase core engine: Histogram< T > Class Template Reference
Histogram< T > Class Template Reference
A Histogram.
#include <histo.hh>
Classes
class iterator
A HistogramBin iterator.
Public Member Functions
template<typename G >
Histogram (G &generator, size_t n=25)
Build a histogram.
Histogram (size_t n=25)
Build a default histogram.
~Histogram ()
void add (T amount, size_t count=1)
Add a value to this histogram.
const HistogramBin< T > * getBin (T amount)
Get the bin servicing the given sized input.
void reset ()
Set all bins to 0.
size_t total ()
Get the total number of samples counted.
iterator begin () const
Get an iterator from the beginning of a histogram bin.
iterator end () const
Get the iterator at the end of the histogram bin.
Friends
template<typename Ttype >
std::ostream & operator<< (std::ostream &out, const Histogram< Ttype > &b)
Detailed Description
template<typename T>
class Histogram< T >
A Histogram.
Constructor & Destructor Documentation
template<typename T> template<typename G > Histogram< T >::Histogram (G & generator, size_t n = 25) [inline]
Build a histogram.
Parameters:
generator a generator for the bins within this bucket
n how many bins this histogram should contain
template<typename T> Histogram< T >::Histogram (size_t n = 25) [inline]
Build a default histogram.
Parameters:
n how many bins this histogram should contain.
template<typename T> Histogram< T >::~Histogram () [inline]
Member Function Documentation
template<typename T> void Histogram< T >::add (T amount, size_t count = 1) [inline]
Add a value to this histogram.
Parameters:
amount the size of the thing being added
count the quantity at this size being added
Referenced by TapBGFetchCallback::callback(), EventuallyPersistentStore::completeBGFetch(), and BlockTimer::~BlockTimer().
template<typename T> iterator Histogram< T >::begin () const [inline]
Get an iterator from the beginning of a histogram bin.
Referenced by add_casted_stat(), and Histogram< hrtime_t >::total().
template<typename T> iterator Histogram< T >::end () const [inline]
Get the iterator at the end of the histogram bin.
Referenced by add_casted_stat(), and Histogram< hrtime_t >::total().
template<typename T> const HistogramBin<T>* Histogram< T >::getBin (T amount) [inline]
Get the bin servicing the given sized input.
template<typename T> void Histogram< T >::reset () [inline]
Set all bins to 0.
Referenced by EPStats::reset().
template<typename T> size_t Histogram< T >::total () [inline]
Get the total number of samples counted.
This is the sum of all counts in each bin.
Friends And Related Function Documentation
template<typename T> template<typename Ttype > std::ostream& operator<< (std::ostream & out, const Histogram< Ttype > & b) [friend]
The documentation for this class was generated from the following file:
histo.hh