membase core engine: ExpiredItemPager Class Reference
ExpiredItemPager Class Reference
Dispatcher job responsible for purging expired items from memory and disk.
#include <item_pager.hh>
Public Member Functions
ExpiredItemPager (EventuallyPersistentStore *s, EPStats &st, size_t stime)
Construct an ExpiredItemPager.
bool callback (Dispatcher &d, TaskId t)
Perform my task.
std::string description ()
Print a human-readable description of this callback.
Detailed Description
Dispatcher job responsible for purging expired items from memory and disk.
Constructor & Destructor Documentation
ExpiredItemPager::ExpiredItemPager (EventuallyPersistentStore * s, EPStats & st, size_t stime) [inline]
Construct an ExpiredItemPager.
Parameters:
s the store (where we'll visit)
st the stats
stime number of seconds to wait between runs
Member Function Documentation
bool ExpiredItemPager::callback (Dispatcher & d, TaskId t) [virtual]
Perform my task.
Parameters:
d the dispatcher running this task
t the task
Returns:
true if the task should run again
Implements DispatcherCallback.
References EventuallyPersistentStore::deleteMany(), PagingVisitor::expired, EPStats::expired, EPStats::expiryPagerRuns, getLogger(), Atomic< T >::incr(), Dispatcher::snooze(), and EventuallyPersistentStore::visit().
std::string ExpiredItemPager::description () [inline, virtual]
Print a human-readable description of this callback.
Implements DispatcherCallback.
The documentation for this class was generated from the following files:
item_pager.hh
item_pager.cc