membase core engine: DispatcherState Class Reference
DispatcherState Class Reference
Snapshot of the state of a dispatcher.
#include <dispatcher.hh>
Public Member Functions
DispatcherState (const std::string &name, enum dispatcher_state st, hrtime_t start, bool running)
const char * getStateName () const
Get the name of the current dispatcher state.
hrtime_t getTaskStart () const
Get the time the current task started.
const std::string getTaskName () const
Get the name of the currently running task.
bool isRunningTask () const
True if the dispatcher is currently running a task.
Detailed Description
Snapshot of the state of a dispatcher.
Constructor & Destructor Documentation
DispatcherState::DispatcherState (const std::string & name, enum dispatcher_state st, hrtime_t start, bool running) [inline]
Member Function Documentation
const char* DispatcherState::getStateName () const [inline]
Get the name of the current dispatcher state.
References dispatcher_running, dispatcher_stopped, and dispatcher_stopping.
Referenced by doDispatcherStat().
const std::string DispatcherState::getTaskName () const [inline]
Get the name of the currently running task.
Referenced by doDispatcherStat().
hrtime_t DispatcherState::getTaskStart () const [inline]
Get the time the current task started.
Referenced by doDispatcherStat().
bool DispatcherState::isRunningTask () const [inline]
True if the dispatcher is currently running a task.
Referenced by doDispatcherStat().
The documentation for this class was generated from the following file:
dispatcher.hh