membase core engine: SyncObject Class Reference
SyncObject Class Reference
Abstraction built on top of pthread mutexes.
#include <syncobject.hh>
Public Member Functions
SyncObject ()
~SyncObject ()
void wait ()
bool wait (const struct timeval &tv)
bool wait (const double secs)
void notify ()
Detailed Description
Abstraction built on top of pthread mutexes.
Constructor & Destructor Documentation
SyncObject::SyncObject () [inline]
SyncObject::~SyncObject () [inline]
Member Function Documentation
void SyncObject::notify () [inline]
Referenced by RememberingCallback< T >::callback(), EventuallyPersistentEngine::createTapQueue(), EventuallyPersistentEngine::performTapOp(), Dispatcher::run(), Dispatcher::schedule(), Dispatcher::stop(), and Dispatcher::wake().
bool SyncObject::wait (const struct timeval & tv) [inline]
References Mutex::mutex, and Mutex::setHolder().
bool SyncObject::wait (const double secs) [inline]
References advance_tv(), and wait().
void SyncObject::wait (void) [inline]
References Mutex::mutex, and Mutex::setHolder().
Referenced by Dispatcher::run(), wait(), and RememberingCallback< T >::waitForValue().
The documentation for this class was generated from the following file:
syncobject.hh