membase core engine: VBucketMap Class Reference
VBucketMap Class Reference
A map of known vbuckets.
#include <vbucket.hh>
Public Member Functions
VBucketMap ()
void addBucket (RCPtr< VBucket > &b)
HashTableStatVisitor removeBucket (int id)
void addBuckets (const std::vector< VBucket * > &newBuckets)
RCPtr< VBucket > getBucket (int id) const
size_t getSize () const
std::vector< int > getBuckets (void)
bool isBucketDeletion (int id)
void setBucketDeletion (int id, bool delBucket)
Detailed Description
A map of known vbuckets.
Constructor & Destructor Documentation
VBucketMap::VBucketMap () [inline]
Member Function Documentation
void VBucketMap::addBucket (RCPtr< VBucket > & b) [inline]
Referenced by addBuckets(), LoadStorageKVPairCallback::callback(), EventuallyPersistentStore::EventuallyPersistentStore(), LoadStorageKVPairCallback::initVBucket(), and EventuallyPersistentStore::setVBucketState().
void VBucketMap::addBuckets (const std::vector< VBucket * > & newBuckets) [inline]
References addBucket().
RCPtr<VBucket> VBucketMap::getBucket (int id) const [inline]
Referenced by LoadStorageKVPairCallback::callback(), EventuallyPersistentStore::completeVBucketDeletion(), EventuallyPersistentStore::deleteVBucket(), EventuallyPersistentStore::getHashLocks(), EventuallyPersistentStore::getHashSize(), EventuallyPersistentStore::getVBucket(), LoadStorageKVPairCallback::initVBucket(), EventuallyPersistentStore::setVBucketState(), EventuallyPersistentStore::visit(), and EventuallyPersistentStore::visitDepth().
std::vector<int> VBucketMap::getBuckets (void) [inline]
Referenced by EventuallyPersistentStore::reset().
size_t VBucketMap::getSize () const [inline]
Referenced by EventuallyPersistentStore::visit().
bool VBucketMap::isBucketDeletion (int id) [inline]
Referenced by EventuallyPersistentStore::completeVBucketDeletion().
HashTableStatVisitor VBucketMap::removeBucket (int id) [inline]
Referenced by EventuallyPersistentStore::deleteVBucket().
void VBucketMap::setBucketDeletion (int id, bool delBucket) [inline]
Referenced by EventuallyPersistentStore::completeVBucketDeletion(), and EventuallyPersistentStore::deleteVBucket().
The documentation for this class was generated from the following file:
vbucket.hh