membase core engine: HashTable Class Reference
HashTable Class Reference
A container of StoredValue instances.
#include <stored-value.hh>
Public Member Functions
HashTable (EPStats &st, size_t s=0, size_t l=0, enum stored_value_type t=featured)
Create a HashTable.
~HashTable ()
size_t memorySize ()
size_t getSize (void)
Get the number of hash table buckets this hash table has.
size_t getNumLocks (void)
Get the number of locks in this hash table.
size_t getNumItems (void)
Get the number of items within this hash table.
size_t clear (bool deactivate=false)
Clear the hash table.
StoredValue * find (std::string &key)
Find the item with the given key.
mutation_type_t set (const Item &val, bool honorMemLimit=true)
Set a new Item into this hashtable.
add_type_t add (const Item &val, bool isDirty=true, bool storeVal=true)
Add an item to the hash table iff it doesn't already exist.
mutation_type_t softDelete (const std::string &key)
Mark the given record logically deleted.
mutation_type_t unlocked_softDelete (const std::string &key, int bucket_num)
Unlocked implementation of softDelete.
StoredValue * unlocked_find (const std::string &key, int bucket_num, bool wantsDeleted=false)
Find an item within a specific bucket assuming you already locked the bucket.
int bucket (const char *str, const size_t len)
Get the bucket number for the given C string key.
int bucket (const std::string &s)
Get the bucket number for the given string.
Mutex & getMutexForLock (int lock_num)
Get the Mutex for the given lock.
Mutex & getMutex (int bucket_num)
Get the mutex for a bucket (for doing your own lock management).
bool unlocked_del (const std::string &key, int bucket_num)
Delete a key from the cache without trying to lock the cache first (Please note that you MUST acquire the mutex before calling this function!!!
bool del (const std::string &key)
Delete the item with the given key.
void visit (HashTableVisitor &visitor)
Visit all items within this hashtable.
void visitDepth (HashTableDepthVisitor &visitor)
Visit all items within this call with a depth visitor.
Static Public Member Functions
static size_t getNumBuckets (size_t s)
Get the number of buckets that should be used for initialization.
static size_t getNumLocks (size_t s)
Get the number of locks that should be used for initialization.
static void setDefaultNumBuckets (size_t)
Set the default number of buckets.
static void setDefaultNumLocks (size_t)
Set the default number of locks.
static bool setDefaultStorageValueType (const char *t)
Set the stored value type by name.
static void setDefaultStorageValueType (enum stored_value_type)
Set the default StoredValue type by enum value.
static enum stored_value_type getDefaultStorageValueType ()
Get the default StoredValue type.
static const char * getDefaultStorageValueTypeStr ()
Get the default StoredValue type as a string.
Detailed Description
A container of StoredValue instances.
Constructor & Destructor Documentation
HashTable::HashTable (EPStats & st, size_t s = 0, size_t l = 0, enum stored_value_type t = featured) [inline]
Create a HashTable.
Parameters:
s the number of hash table buckets
l the number of locks in the hash table
t the type of StoredValues this hash table will contain
References getNumBuckets(), getNumLocks(), StoredValue::size(), and StoredValue::StoredValueFactory.
HashTable::~HashTable () [inline]
Member Function Documentation
add_type_t HashTable::add (const Item & val, bool isDirty = true, bool storeVal = true) [inline]
Add an item to the hash table iff it doesn't already exist.
Parameters:
val the item to store
isDirty true if the item should be marked dirty on store
storeVal true if the value should be stored (paged-in)
Returns:
an indication of what happened
References ADD_UNDEL, StoredValue::ejectValue(), Item::getCas(), Item::getExptime(), Item::getFlags(), Item::getKey(), Item::getValue(), StoredValue::isDeleted(), StoredValue::isDirty(), StoredValue::markDirty(), Item::setCas(), and StoredValue::setValue().
int HashTable::bucket (const char * str, const size_t len) [inline]
Get the bucket number for the given C string key.
Parameters:
str the string
len the number of bytes to use for hash computation
Returns:
the bucket number for this key
References StoredValue::size().
int HashTable::bucket (const std::string & s) [inline]
Get the bucket number for the given string.
Parameters:
s the key
Returns:
the bucket number for this key
size_t HashTable::clear (bool deactivate = false)
Clear the hash table.
Parameters:
deactivate true when this hash table is being destroyed completely
Returns:
the number of items removed
References Atomic< T >::set().
bool HashTable::del (const std::string & key) [inline]
Delete the item with the given key.
Parameters:
key the key to delete
Returns:
true if the item existed before this call
StoredValue* HashTable::find (std::string & key) [inline]
Find the item with the given key.
Parameters:
key the key to find
Returns:
a pointer to a StoredValue -- NULL if not found
enum stored_value_type HashTable::getDefaultStorageValueType () [static]
Get the default StoredValue type.
Referenced by getDefaultStorageValueTypeStr(), and EventuallyPersistentEngine::initialize().
const char * HashTable::getDefaultStorageValueTypeStr () [static]
Get the default StoredValue type as a string.
References featured, getDefaultStorageValueType(), and small.
Mutex& HashTable::getMutex (int bucket_num) [inline]
Get the mutex for a bucket (for doing your own lock management).
Parameters:
bucket_num the bucket number
Returns:
the Mutex covering that bucket
Referenced by visit(), and visitDepth().
Mutex& HashTable::getMutexForLock (int lock_num) [inline]
Get the Mutex for the given lock.
Parameters:
lock_num the lock number to get
Returns:
the Mutex
size_t HashTable::getNumBuckets (size_t n = 0) [static]
Get the number of buckets that should be used for initialization.
Get the number of buckets for a hash table.
Parameters:
s if 0, return the default number of buckets, else return s
n the desired number of buckets, if 0, use the default
Returns:
the number of buckets to create
References getDefault().
Referenced by HashTable().
size_t HashTable::getNumItems (void) [inline]
Get the number of items within this hash table.
size_t HashTable::getNumLocks (void) [inline]
Get the number of locks in this hash table.
Referenced by HashTable().
size_t HashTable::getNumLocks (size_t n = 0) [static]
Get the number of locks that should be used for initialization.
Get the number of locks for a hash table.
Parameters:
s if 0, return the default number of locks, else return s
n the desired number of locks, if 0, use the default
Returns:
the number of locks to create
References getDefault().
size_t HashTable::getSize (void) [inline]
Get the number of hash table buckets this hash table has.
size_t HashTable::memorySize () [inline]
References StoredValue::size().
Referenced by VBucket::VBucket(), and VBucket::~VBucket().
mutation_type_t HashTable::set (const Item & val, bool honorMemLimit = true) [inline]
Set a new Item into this hashtable.
Parameters:
the Item to store
Returns:
a result indicating the status of the store
References ep_current_time, StoredValue::getCas(), StoredValue::isClean(), StoredValue::isLocked(), StoredValue::setValue(), StoredValue::unlock(), and WAS_CLEAN.
void HashTable::setDefaultNumBuckets (size_t to) [static]
Set the default number of buckets.
Set the default number of hashtable buckets.
Referenced by EventuallyPersistentEngine::initialize().
void HashTable::setDefaultNumLocks (size_t to) [static]
Set the default number of locks.
Set the default number of hashtable locks.
Referenced by EventuallyPersistentEngine::initialize().
bool HashTable::setDefaultStorageValueType (const char * t) [static]
Set the stored value type by name.
Parameters:
t either "small" or "featured"
true if this type is not handled.
References featured, and small.
Referenced by EventuallyPersistentEngine::initialize().
void HashTable::setDefaultStorageValueType (enum stored_value_type t) [static]
Set the default StoredValue type by enum value.
mutation_type_t HashTable::softDelete (const std::string & key) [inline]
Mark the given record logically deleted.
Parameters:
key the key of the item to delete
Returns:
an indicator of what the deletion did
bool HashTable::unlocked_del (const std::string & key, int bucket_num) [inline]
Delete a key from the cache without trying to lock the cache first (Please note that you MUST acquire the mutex before calling this function!!!
Parameters:
key the key to delete
bucket_num the bucket to look in (must already be locked)
Returns:
true if an object was deleted, false otherwise
References ep_current_time, StoredValue::hasKey(), StoredValue::isLocked(), and StoredValue::size().
StoredValue* HashTable::unlocked_find (const std::string & key, int bucket_num, bool wantsDeleted = false) [inline]
Find an item within a specific bucket assuming you already locked the bucket.
Parameters:
key the key of the item to find
bucket_Num the bucket number
Returns:
a pointer to a StoredValue -- NULL if not found
References StoredValue::hasKey(), and StoredValue::isDeleted().
mutation_type_t HashTable::unlocked_softDelete (const std::string & key, int bucket_num) [inline]
Unlocked implementation of softDelete.
References StoredValue::del(), StoredValue::isClean(), and WAS_CLEAN.
void HashTable::visit (HashTableVisitor & visitor)
Visit all items within this hashtable.
References Atomic< T >::get(), getMutex(), HashTableVisitor::shouldContinue(), LockHolder::unlock(), and HashTableVisitor::visit().
void HashTable::visitDepth (HashTableDepthVisitor & visitor)
Visit all items within this call with a depth visitor.
References Atomic< T >::get(), getMutex(), and HashTableDepthVisitor::visit().
Referenced by VBucket::size().
The documentation for this class was generated from the following files:
stored-value.hh
stored-value.cc