membase core engine: VKeyStatBGFetchCallback Class Reference
VKeyStatBGFetchCallback Class Reference
Public Member Functions
VKeyStatBGFetchCallback (EventuallyPersistentStore *e, const std::string &k, uint16_t vbid, uint64_t r, const void *c, shared_ptr< Callback< GetValue > > cb)
bool callback (Dispatcher &d, TaskId t)
Perform my task.
std::string description ()
Print a human-readable description of this callback.
Constructor & Destructor Documentation
VKeyStatBGFetchCallback::VKeyStatBGFetchCallback (EventuallyPersistentStore * e, const std::string & k, uint16_t vbid, uint64_t r, const void * c, shared_ptr< Callback< GetValue > > cb) [inline]
Member Function Documentation
bool VKeyStatBGFetchCallback::callback (Dispatcher & d, TaskId t) [inline, virtual]
Perform my task.
Parameters:
d the dispatcher running this task
t the task
Returns:
true if the task should run again
Implements DispatcherCallback.
References RememberingCallback< T >::fired, StrategicSqlite3::get(), EventuallyPersistentStore::getUnderlying(), RememberingCallback< T >::val, and RememberingCallback< T >::waitForValue().
std::string VKeyStatBGFetchCallback::description () [inline, virtual]
Print a human-readable description of this callback.
Implements DispatcherCallback.
The documentation for this class was generated from the following file:
ep.cc