membase core engine: Priority Class Reference
Priority Class Reference
Task priority definition.
#include <priority.hh>
Public Member Functions
bool operator== (const Priority &other) const
bool operator< (const Priority &other) const
bool operator> (const Priority &other) const
const std::string & toString () const
Return a priority name.
int getPriorityValue () const
Return an integer value that represents a priority.
Static Public Attributes
static const Priority BgFetcherPriority
static const Priority TapBgFetcherPriority
static const Priority SetVBucketPriority
static const Priority VKeyStatBgFetcherPriority
static const Priority NotifyVBStateChangePriority
static const Priority FlusherPriority
static const Priority ItemPagerPriority
static const Priority VBucketDeletionPriority
Protected Member Functions
Priority (const char *nm, int p)
Priority (const Priority &)
void operator= (const Priority &)
Protected Attributes
std::string name
int priority
Detailed Description
Task priority definition.
Constructor & Destructor Documentation
Priority::Priority (const char * nm, int p) [inline, protected]
Priority::Priority (const Priority &) [protected]
Member Function Documentation
int Priority::getPriorityValue () const [inline]
Return an integer value that represents a priority.
Returns:
a priority value
References priority.
Referenced by operator<(), operator==(), operator>(), and Dispatcher::schedule().
bool Priority::operator< (const Priority & other) const [inline]
References getPriorityValue(), and priority.
void Priority::operator= (const Priority &) [protected]
bool Priority::operator== (const Priority & other) const [inline]
References getPriorityValue(), and priority.
bool Priority::operator> (const Priority & other) const [inline]
References getPriorityValue(), and priority.
const std::string& Priority::toString () const [inline]
Return a priority name.
Returns:
a priority name
References name.
Member Data Documentation
const Priority Priority::BgFetcherPriority [static]
Referenced by EventuallyPersistentStore::bgFetch().
const Priority Priority::FlusherPriority [static]
const Priority Priority::ItemPagerPriority [static]
Referenced by EventuallyPersistentEngine::initialize().
std::string Priority::name [protected]
Referenced by toString().
const Priority Priority::NotifyVBStateChangePriority [static]
Referenced by EventuallyPersistentStore::setVBucketState().
int Priority::priority [protected]
Referenced by getPriorityValue(), operator<(), operator==(), and operator>().
const Priority Priority::SetVBucketPriority [static]
Referenced by EventuallyPersistentStore::completeSetVBState(), and EventuallyPersistentStore::setVBucketState().
const Priority Priority::TapBgFetcherPriority [static]
const Priority Priority::VBucketDeletionPriority [static]
Referenced by EventuallyPersistentStore::completeVBucketDeletion(), and EventuallyPersistentStore::deleteVBucket().
const Priority Priority::VKeyStatBgFetcherPriority [static]
Referenced by EventuallyPersistentStore::getFromUnderlying().
The documentation for this class was generated from the following files:
priority.hh
priority.cc