membase core engine: VBucket Class Reference
VBucket Class Reference
An individual vbucket.
#include <vbucket.hh>
Public Member Functions
VBucket (int i, vbucket_state_t initialState, EPStats &st)
~VBucket ()
int getId (void) const
vbucket_state_t getState (void) const
void setState (vbucket_state_t to, SERVER_HANDLE_V1 *sapi)
const char * getStateString (void) const
bool addPendingOp (const void *cookie)
void fireAllOps (SERVER_HANDLE_V1 *sapi)
size_t size (void)
Static Public Member Functions
static const char * toString (vbucket_state_t s)
Public Attributes
HashTable ht
Static Public Attributes
static const vbucket_state_t ACTIVE = static_cast<vbucket_state_t>(htonl(active))
static const vbucket_state_t REPLICA = static_cast<vbucket_state_t>(htonl(replica))
static const vbucket_state_t PENDING = static_cast<vbucket_state_t>(htonl(pending))
static const vbucket_state_t DEAD = static_cast<vbucket_state_t>(htonl(dead))
Detailed Description
An individual vbucket.
Constructor & Destructor Documentation
VBucket::VBucket (int i, vbucket_state_t initialState, EPStats & st) [inline]
References Atomic< T >::get(), ht, Atomic< T >::incr(), HashTable::memorySize(), and EPStats::memOverhead.
VBucket::~VBucket () [inline]
References Atomic< T >::decr(), Atomic< T >::get(), getLogger(), ht, HashTable::memorySize(), and EPStats::memOverhead.
Member Function Documentation
bool VBucket::addPendingOp (const void * cookie) [inline]
References gethrtime(), EPStats::pendingOps, and EPStats::pendingOpsTotal.
void VBucket::fireAllOps (SERVER_HANDLE_V1 * sapi)
int VBucket::getId (void) const [inline]
vbucket_state_t VBucket::getState (void) const [inline]
const char* VBucket::getStateString (void) const [inline]
References toString().
void VBucket::setState (vbucket_state_t to, SERVER_HANDLE_V1 * sapi)
References getLogger(), and toString().
size_t VBucket::size (void) [inline]
References ht, HashTableDepthStatVisitor::size, and HashTable::visitDepth().
static const char* VBucket::toString (vbucket_state_t s) [inline, static]
Referenced by VBucketHolder::addBucket(), getStateString(), setState(), EventuallyPersistentStore::setVBucketState(), and StatVBucketVisitor::visitBucket().
Member Data Documentation
const vbucket_state_t VBucket::ACTIVE = static_cast<vbucket_state_t>(htonl(active)) [static]
const vbucket_state_t VBucket::DEAD = static_cast<vbucket_state_t>(htonl(dead)) [static]
HashTable VBucket::ht
Referenced by size(), VBucket(), and ~VBucket().
const vbucket_state_t VBucket::PENDING = static_cast<vbucket_state_t>(htonl(pending)) [static]
const vbucket_state_t VBucket::REPLICA = static_cast<vbucket_state_t>(htonl(replica)) [static]
The documentation for this class was generated from the following files:
vbucket.hh
vbucket.cc