membase core engine: common.hh File Reference
common.hh File Reference
#include <cassert>
#include <errno.h>
#include <stdlib.h>
#include <stdint.h>
#include <ctype.h>
#include <inttypes.h>
#include <limits.h>
#include <math.h>
#include <sys/time.h>
#include <memcached/engine.h>
#include "config.h"
#include <memory>
#include <tr1/memory>
#include <sstream>
Defines
#define UINT16_MAX 65535
#define DISALLOW_COPY_AND_ASSIGN(TypeName)
#define GIGANTOR ((size_t)1<<(sizeof(size_t)*8-1))
Functions
EXTENSION_LOGGER_DESCRIPTOR * getLogger (void)
void advance_tv (struct timeval &tv, const double secs)
bool less_tv (const struct timeval &tv1, const struct timeval &tv2)
bool parseUint16 (const char *in, uint16_t *out)
std::string hrtime2text (hrtime_t time)
Convert a time (in ns) to a human readable form...
Define Documentation
#define DISALLOW_COPY_AND_ASSIGN (TypeName)
Value:
TypeName(const TypeName&);                  \
    void operator=(const TypeName&)
#define GIGANTOR ((size_t)1<<(sizeof(size_t)*8-1))
Referenced by main().
#define UINT16_MAX 65535
Referenced by parseUint16().
Function Documentation
void advance_tv (struct timeval & tv, const double secs) [inline]
Referenced by SyncObject::wait().
EXTENSION_LOGGER_DESCRIPTOR* getLogger (void)
Referenced by VBucketHolder::addBucket(), EventuallyPersistentStore::bgFetch(), ExpiredItemPager::callback(), ItemPager::callback(), LoadStorageKVPairCallback::callback(), EventuallyPersistentStore::completeBGFetch(), EventuallyPersistentStore::completeSetVBState(), EventuallyPersistentStore::completeVBucketDeletion(), EventuallyPersistentEngine::createTapQueue(), SqliteStrategy::doFile(), SqliteEvaluator::eval(), evictKey(), EventuallyPersistentEngine::handleDisconnect(), Flusher::initialize(), GetlExtension::initialize(), EventuallyPersistentEngine::initialize(), launch_dispatcher_thread(), Dispatcher::run(), VBucket::setState(), EventuallyPersistentEngine::startFlusher(), Flusher::step(), Dispatcher::stop(), EventuallyPersistentEngine::stopFlusher(), EventuallyPersistentStore::warmup(), Flusher::~Flusher(), and VBucket::~VBucket().
std::string hrtime2text (hrtime_t time) [inline]
Convert a time (in ns) to a human readable form...
Parameters:
time the time in nanoseconds
buffer where to store the result
size the size of the buffer
Returns:
buffer
bool less_tv (const struct timeval & tv1, const struct timeval & tv2) [inline]
Referenced by CompareTasksByDueDate::operator()(), and Dispatcher::run().
bool parseUint16 (const char * in, uint16_t * out) [inline]
References UINT16_MAX.
Referenced by deleteVBucket(), getVbucket(), and setVbucket().