membase core engine: config_static.h File Reference
config_static.h File Reference
#include <inttypes.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <poll.h>
Defines
#define EXPORT_FUNCTION
#define SQLITE_HAS_CODEC 0
Typedefs
typedef uint64_t hrtime_t
Functions
hrtime_t gethrtime (void)
Define Documentation
#define EXPORT_FUNCTION
#define SQLITE_HAS_CODEC 0
Typedef Documentation
typedef uint64_t hrtime_t
Function Documentation
hrtime_t gethrtime (void)
References clock_gettime(), and CLOCK_MONOTONIC.
Referenced by VBucket::addPendingOp(), TapBGFetchCallback::callback(), BGFetchCallback::callback(), EventuallyPersistentStore::completeBGFetch(), doDispatcherStat(), Dispatcher::run(), and BlockTimer::~BlockTimer().