membase core engine: ep.hh File Reference
ep.hh File Reference
#include <pthread.h>
#include <assert.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <stdexcept>
#include <iostream>
#include <queue>
#include <limits>
#include <unistd.h>
#include <set>
#include <list>
#include <algorithm>
#include <memcached/engine.h>
#include "stats.hh"
#include "locks.hh"
#include "sqlite-kvstore.hh"
#include "stored-value.hh"
#include "atomic.hh"
#include "dispatcher.hh"
#include "vbucket.hh"
Classes
class QueuedItem
class VBucketVisitor
vbucket-aware hashtable visitor.
class LoadStorageKVPairCallback
Helper class used to insert items into the storage by using the KVStore::dump method to load items from the database.
class EventuallyPersistentStore
Defines
#define DEFAULT_TXN_SIZE 50000
#define MAX_TXN_SIZE 10000000
#define MAX_DATA_AGE_PARAM 86400
#define MAX_BG_FETCH_DELAY 900
Enumerations
enum queue_operation { queue_op_set, queue_op_del, queue_op_flush }
Functions
EXTENSION_LOGGER_DESCRIPTOR * getLogger (void)
time_t ep_real_time ()
Variables
rel_time_t(* ep_current_time)()
time_t(* ep_abs_time)(rel_time_t)
Define Documentation
#define DEFAULT_TXN_SIZE 50000
Referenced by EventuallyPersistentStore::EventuallyPersistentStore().
#define MAX_BG_FETCH_DELAY 900
Referenced by setFlushParam().
#define MAX_DATA_AGE_PARAM 86400
Referenced by setFlushParam().
#define MAX_TXN_SIZE 10000000
Referenced by setFlushParam().
Enumeration Type Documentation
enum queue_operation
Enumerator:
queue_op_set
queue_op_del
queue_op_flush
Function Documentation
time_t ep_real_time ()
References ep_abs_time, and ep_current_time.
Referenced by StrategicSqlite3::dump(), Flusher::initialize(), and EventuallyPersistentEngine::initialize().
EXTENSION_LOGGER_DESCRIPTOR* getLogger (void)
References extensionApi.
Variable Documentation
time_t(* ep_abs_time)(rel_time_t)
Referenced by EventuallyPersistentEngine::arithmetic(), create_instance(), ep_real_time(), EventuallyPersistentStore::getKeyStats(), and EventuallyPersistentEngine::itemAllocate().
rel_time_t(* ep_current_time)()