membase core engine: ep.cc File Reference
ep.cc File Reference
#include "config.h"
#include <vector>
#include <time.h>
#include <string.h>
#include <iostream>
#include <functional>
#include "ep.hh"
#include "flusher.hh"
#include "locks.hh"
#include "dispatcher.hh"
#include "sqlite-kvstore.hh"
#include "ep_engine.h"
#include "item_pager.hh"
Classes
class BGFetchCallback
class VKeyStatBGFetchCallback
class SetVBStateCallback
class NotifyVBStateChangeCallback
class VBucketDeletionCallback
class VerifyStoredVisitor
class Deleter
class PersistenceCallback
Functions
static rel_time_t uninitialized_current_time (void)
static time_t default_abs_time (rel_time_t offset)
time_t ep_real_time ()
Variables
rel_time_t(* ep_current_time)() = uninitialized_current_time
time_t(* ep_abs_time)(rel_time_t) = default_abs_time
Function Documentation
static time_t default_abs_time (rel_time_t offset) [static]
References ep_current_time.
time_t ep_real_time ()
References ep_abs_time, and ep_current_time.
Referenced by StrategicSqlite3::dump(), Flusher::initialize(), and EventuallyPersistentEngine::initialize().
static rel_time_t uninitialized_current_time (void) [static]
Variable Documentation
time_t(* ep_abs_time)(rel_time_t) = default_abs_time
Referenced by EventuallyPersistentEngine::arithmetic(), create_instance(), ep_real_time(), EventuallyPersistentStore::getKeyStats(), and EventuallyPersistentEngine::itemAllocate().
rel_time_t(* ep_current_time)() = uninitialized_current_time
Referenced by create_instance(), default_abs_time(), ep_real_time(), EventuallyPersistentStore::get(), StoredValue::markDirty(), HashTable::set(), and HashTable::unlocked_del().