membase core engine: ep_testsuite.cc File Reference
ep_testsuite.cc File Reference
#include <iostream>
#include <sstream>
#include <map>
#include <string>
#include <vector>
#include <cstdlib>
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <pthread.h>
#include <netinet/in.h>
#include <memcached/engine.h>
#include <memcached/engine_testapp.h>
#include "ep_testsuite.h"
#include "command_ids.h"
Classes
class ThreadData
struct handle_pair
Defines
#define check(expr, msg) static_cast<void>((expr) ? 0 : abort_msg(#expr, msg, __LINE__))
#define WHITESPACE_DB "whitespace sucks.db"
Functions
bool abort_msg (const char *expr, const char *msg, int line)
protocol_binary_response_status last_status (static_cast< protocol_binary_response_status >(0))
static void rmdb (void)
static bool teardown (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static void decayingSleep (useconds_t *sleepTime)
static ENGINE_ERROR_CODE storeCasVb11 (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, const void *cookie, ENGINE_STORE_OPERATION op, const char *key, const char *value, size_t vlen, uint32_t flags, item **outitem, uint64_t casIn, uint16_t vb)
static ENGINE_ERROR_CODE store (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, const void *cookie, ENGINE_STORE_OPERATION op, const char *key, const char *value, item **outitem, uint64_t casIn=0, uint16_t vb=0)
static ENGINE_ERROR_CODE verify_vb_key (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, const char *key, uint16_t vbucket)
static ENGINE_ERROR_CODE verify_key (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, const char *key)
static bool get_value (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, const char *key, item_info *info)
static bool get_key (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, item *i, std::string &key)
static enum test_result check_key_value (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, const char *key, const char *val, size_t vlen, bool checkcrlf=false, uint16_t vbucket=0)
static void add_stats (const char *key, const uint16_t klen, const char *val, const uint32_t vlen, const void *cookie)
static bool add_response (const void *key, uint16_t keylen, const void *ext, uint8_t extlen, const void *body, uint32_t bodylen, uint8_t datatype, uint16_t status, uint64_t cas, const void *cookie)
static
protocol_binary_request_header * create_packet (uint8_t opcode, const char *key, const char *val)
static void evict_key (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, const char *key, uint16_t vbucketId=0, const char *msg=NULL)
static bool set_vbucket_state (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, uint16_t vb, const char *state)
static bool set_flush_param (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, const char *param, const char *val)
static bool verify_vbucket_state (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, uint16_t vb, const char *expected, bool mute=false)
static bool verify_vbucket_missing (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, uint16_t vb)
static int get_int_stat (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, const char *statname, const char *statkey=NULL)
static void verify_curr_items (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, int exp, const char *msg)
static void wait_for_stat_change (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, const char *stat, int initial)
static void wait_for_flusher_to_settle (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static void wait_for_persisted_value (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, const char *key, const char *val, uint16_t vbucketId=0)
static enum test_result test_wrong_vb_mutation (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, ENGINE_STORE_OPERATION op)
static enum test_result test_pending_vb_mutation (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, ENGINE_STORE_OPERATION op)
static enum test_result test_replica_vb_mutation (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, ENGINE_STORE_OPERATION op)
static enum test_result test_get_miss (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_init_fail (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_set (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static void * conc_del_set_thread (void *arg)
static enum test_result test_conc_set (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_set_get_hit (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_set_get_hit_bin (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_set_change_flags (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_cas (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_add (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_replace (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_incr_miss (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_incr_default (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_append (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_prepend (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_incr (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_flush (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_flush_stats (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_flush_multiv (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_flush_restart (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_flush_multiv_restart (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_delete (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_set_delete (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_bug2509 (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_delete_set (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_restart (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_restart_bin_val (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_wrong_vb_get (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_get_pending (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_get_replica (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_wrong_vb_incr (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_incr_pending (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_incr_replica (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_wrong_vb_set (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_wrong_vb_cas (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_wrong_vb_add (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_wrong_vb_replace (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_wrong_vb_append (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_wrong_vb_prepend (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_wrong_vb_del (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_expiry (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_expiry_loader (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_expiry_flush (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_del_pending (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_del_replica (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_alloc_limit (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_whitespace_db (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_db_shards (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_memory_limit (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vbucket_get_miss (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vbucket_get (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vbucket_create (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vbucket_destroy (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vbucket_destroy_stats (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vbucket_destroy_restart (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_set_pending (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_add_pending (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_cas_pending (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_append_pending (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_prepend_pending (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_set_replica (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_replace_replica (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_replace_pending (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_add_replica (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_cas_replica (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_append_replica (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vb_prepend_replica (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_tap_rcvr_mutate (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_tap_rcvr_mutate_dead (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_tap_rcvr_mutate_pending (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_tap_rcvr_mutate_replica (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result verify_item (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1, item *i, const char *key, size_t klen, const char *val, size_t vlen)
static enum test_result test_tap_stream (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_tap_filter_stream (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_tap_ack_stream (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_novb0 (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_stats (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_mem_stats (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_io_stats (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_bg_stats (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_key_stats (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_vkey_stats (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_curr_items (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_value_eviction (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_duplicate_items_disk (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_disk_gt_ram_golden (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_disk_gt_ram_paged_rm (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_disk_gt_ram_incr (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_disk_gt_ram_update_paged_out (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_disk_gt_ram_delete_paged_out (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static void * bg_set_thread (void *arg)
static void * bg_del_thread (void *arg)
static void * bg_incr_thread (void *arg)
static enum test_result test_disk_gt_ram_set_race (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_disk_gt_ram_incr_race (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_disk_gt_ram_rm_race (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static bool epsilon (int val, int target, int ep=5)
static enum test_result test_max_size_settings (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
static enum test_result test_validate_engine_handle (ENGINE_HANDLE *h, ENGINE_HANDLE_V1 *h1)
MEMCACHED_PUBLIC_API
engine_test_t * get_tests (void)
MEMCACHED_PUBLIC_API bool setup_suite (struct test_harness *th)
Variables
char * last_key = NULL
char * last_body = NULL
std::map< std::string,
std::string > vals
struct test_harness testHarness
Define Documentation
#define check (expr, msg) static_cast<void>((expr) ? 0 : abort_msg(#expr, msg, __LINE__))
Referenced by bg_del_thread(), bg_incr_thread(), bg_set_thread(), check_key_value(), conc_del_set_thread(), evict_key(), get_int_stat(), storeCasVb11(), test_add(), test_alloc_limit(), test_append(), test_bg_stats(), test_bug2509(), test_cas(), test_curr_items(), test_db_shards(), test_delete(), test_delete_set(), test_disk_gt_ram_delete_paged_out(), test_disk_gt_ram_golden(), test_disk_gt_ram_incr(), test_disk_gt_ram_paged_rm(), test_disk_gt_ram_rm_race(), test_disk_gt_ram_update_paged_out(), test_duplicate_items_disk(), test_expiry(), test_expiry_flush(), test_expiry_loader(), test_flush(), test_flush_multiv(), test_flush_multiv_restart(), test_flush_restart(), test_flush_stats(), test_get_miss(), test_incr(), test_incr_default(), test_incr_miss(), test_init_fail(), test_io_stats(), test_key_stats(), test_max_size_settings(), test_mem_stats(), test_memory_limit(), test_novb0(), test_pending_vb_mutation(), test_prepend(), test_replace(), test_replica_vb_mutation(), test_restart(), test_restart_bin_val(), test_set(), test_set_change_flags(), test_set_delete(), test_set_get_hit(), test_set_get_hit_bin(), test_stats(), test_tap_ack_stream(), test_tap_filter_stream(), test_tap_rcvr_mutate(), test_tap_rcvr_mutate_dead(), test_tap_rcvr_mutate_pending(), test_tap_rcvr_mutate_replica(), test_tap_stream(), test_validate_engine_handle(), test_value_eviction(), test_vb_del_pending(), test_vb_del_replica(), test_vb_get_pending(), test_vb_get_replica(), test_vb_incr_pending(), test_vb_incr_replica(), test_vbucket_destroy(), test_vbucket_destroy_restart(), test_vbucket_destroy_stats(), test_vkey_stats(), test_whitespace_db(), test_wrong_vb_del(), test_wrong_vb_get(), test_wrong_vb_incr(), test_wrong_vb_mutation(), verify_item(), verify_vbucket_missing(), and wait_for_persisted_value().
#define WHITESPACE_DB "whitespace sucks.db"
Referenced by get_tests(), and test_whitespace_db().
Function Documentation
bool abort_msg (const char * expr, const char * msg, int line)
static bool add_response (const void * key, uint16_t keylen, const void * ext, uint8_t extlen, const void * body, uint32_t bodylen, uint8_t datatype, uint16_t status, uint64_t cas, const void * cookie) [static]
References last_status().
Referenced by evict_key(), set_flush_param(), set_vbucket_state(), test_curr_items(), test_duplicate_items_disk(), test_value_eviction(), test_vbucket_destroy(), test_vbucket_destroy_restart(), test_vbucket_destroy_stats(), and verify_vbucket_state().
static void add_stats (const char * key, const uint16_t klen, const char * val, const uint32_t vlen, const void * cookie) [static]
Referenced by get_int_stat(), test_db_shards(), test_key_stats(), test_stats(), test_vkey_stats(), test_whitespace_db(), and verify_vbucket_missing().
static void* bg_del_thread (void * arg) [static]
References check, ThreadData::h, and ThreadData::h1.
Referenced by test_disk_gt_ram_rm_race().
static void* bg_incr_thread (void * arg) [static]
References check, ThreadData::h, and ThreadData::h1.
Referenced by test_disk_gt_ram_incr_race().
static void* bg_set_thread (void * arg) [static]
References check, ThreadData::h, ThreadData::h1, and store().
Referenced by test_disk_gt_ram_set_race().
static enum test_result check_key_value (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, const char * key, const char * val, size_t vlen, bool checkcrlf = false, uint16_t vbucket = 0) [static]
References check.
Referenced by test_add(), test_append(), test_bg_stats(), test_cas(), test_delete(), test_delete_set(), test_disk_gt_ram_golden(), test_disk_gt_ram_incr(), test_disk_gt_ram_incr_race(), test_disk_gt_ram_set_race(), test_disk_gt_ram_update_paged_out(), test_duplicate_items_disk(), test_expiry(), test_expiry_loader(), test_flush(), test_flush_multiv(), test_flush_multiv_restart(), test_flush_restart(), test_flush_stats(), test_incr(), test_incr_default(), test_io_stats(), test_mem_stats(), test_memory_limit(), test_prepend(), test_replace(), test_restart(), test_restart_bin_val(), test_set_delete(), test_set_get_hit(), test_set_get_hit_bin(), test_tap_rcvr_mutate(), test_value_eviction(), and test_vbucket_destroy_restart().
static void* conc_del_set_thread (void * arg) [static]
References check, handle_pair::h, handle_pair::h1, and store().
Referenced by test_conc_set().
static protocol_binary_request_header* create_packet (uint8_t opcode, const char * key, const char * val) [static]
Referenced by evict_key(), set_flush_param(), set_vbucket_state(), test_curr_items(), test_duplicate_items_disk(), test_value_eviction(), test_vbucket_destroy(), test_vbucket_destroy_restart(), test_vbucket_destroy_stats(), and verify_vbucket_state().
static void decayingSleep (useconds_t * sleepTime) [inline, static]
Referenced by test_tap_stream(), wait_for_flusher_to_settle(), and wait_for_stat_change().
static bool epsilon (int val, int target, int ep = 5) [static]
Referenced by test_max_size_settings().
static void evict_key (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, const char * key, uint16_t vbucketId = 0, const char * msg = NULL) [static]
References add_response(), check, CMD_EVICT_KEY, create_packet(), and last_status().
Referenced by test_bg_stats(), test_disk_gt_ram_delete_paged_out(), test_disk_gt_ram_golden(), test_disk_gt_ram_incr(), test_disk_gt_ram_incr_race(), test_disk_gt_ram_paged_rm(), test_disk_gt_ram_rm_race(), test_disk_gt_ram_set_race(), test_disk_gt_ram_update_paged_out(), test_duplicate_items_disk(), test_io_stats(), test_mem_stats(), test_tap_stream(), test_value_eviction(), and test_vbucket_destroy_stats().
static int get_int_stat (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, const char * statname, const char * statkey = NULL) [static]
References add_stats(), and check.
Referenced by test_bg_stats(), test_bug2509(), test_conc_set(), test_curr_items(), test_db_shards(), test_disk_gt_ram_delete_paged_out(), test_disk_gt_ram_golden(), test_disk_gt_ram_incr(), test_disk_gt_ram_incr_race(), test_disk_gt_ram_paged_rm(), test_disk_gt_ram_rm_race(), test_disk_gt_ram_set_race(), test_disk_gt_ram_update_paged_out(), test_duplicate_items_disk(), test_expiry(), test_expiry_flush(), test_expiry_loader(), test_flush_stats(), test_io_stats(), test_max_size_settings(), test_mem_stats(), test_memory_limit(), test_replica_vb_mutation(), test_set_delete(), test_tap_filter_stream(), test_tap_stream(), test_value_eviction(), test_vb_del_replica(), test_vb_get_replica(), test_vb_incr_replica(), test_vbucket_destroy_stats(), test_wrong_vb_del(), test_wrong_vb_get(), test_wrong_vb_incr(), test_wrong_vb_mutation(), verify_curr_items(), wait_for_flusher_to_settle(), and wait_for_stat_change().
static bool get_key (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, item * i, std::string & key) [static]
Referenced by test_tap_ack_stream(), test_tap_filter_stream(), and test_tap_stream().
MEMCACHED_PUBLIC_API engine_test_t* get_tests (void)
References WHITESPACE_DB.
static bool get_value (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, const char * key, item_info * info) [static]
Referenced by test_set_change_flags(), and test_tap_ack_stream().
protocol_binary_response_status last_status (static_cast< protocol_binary_response_status > 0)
Referenced by add_response(), evict_key(), set_flush_param(), set_vbucket_state(), test_curr_items(), test_duplicate_items_disk(), test_value_eviction(), test_vbucket_destroy(), test_vbucket_destroy_restart(), test_vbucket_destroy_stats(), and verify_vbucket_state().
static void rmdb (void) [static]
Referenced by teardown().
static bool set_flush_param (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, const char * param, const char * val) [static]
References add_response(), CMD_SET_FLUSH_PARAM, create_packet(), and last_status().
Referenced by test_disk_gt_ram_incr_race(), test_disk_gt_ram_rm_race(), test_disk_gt_ram_set_race(), and test_max_size_settings().
static bool set_vbucket_state (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, uint16_t vb, const char * state) [static]
References add_response(), CMD_SET_VBUCKET, create_packet(), and last_status().
Referenced by test_curr_items(), test_duplicate_items_disk(), test_flush_multiv(), test_flush_multiv_restart(), test_key_stats(), test_pending_vb_mutation(), test_replica_vb_mutation(), test_tap_filter_stream(), test_tap_rcvr_mutate_pending(), test_tap_rcvr_mutate_replica(), test_vb_del_pending(), test_vb_del_replica(), test_vb_get_pending(), test_vb_get_replica(), test_vb_incr_pending(), test_vb_incr_replica(), test_vbucket_create(), test_vbucket_destroy(), test_vbucket_destroy_restart(), test_vbucket_destroy_stats(), and test_vkey_stats().
MEMCACHED_PUBLIC_API bool setup_suite (struct test_harness * th)
References testHarness.
static ENGINE_ERROR_CODE store (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, const void * cookie, ENGINE_STORE_OPERATION op, const char * key, const char * value, item ** outitem, uint64_t casIn = 0, uint16_t vb = 0) [static]
References storeCasVb11().
Referenced by bg_set_thread(), conc_del_set_thread(), Flusher::initialize(), Flusher::step(), test_add(), test_bug2509(), test_cas(), test_curr_items(), test_delete(), test_disk_gt_ram_update_paged_out(), test_duplicate_items_disk(), test_flush(), test_flush_multiv(), test_flush_multiv_restart(), test_flush_restart(), test_flush_stats(), test_incr(), test_key_stats(), test_memory_limit(), test_pending_vb_mutation(), test_replace(), test_replica_vb_mutation(), test_restart(), test_set(), test_set_change_flags(), test_set_delete(), test_set_get_hit(), test_tap_ack_stream(), test_tap_filter_stream(), test_tap_stream(), test_value_eviction(), test_vbucket_destroy_restart(), test_vbucket_destroy_stats(), test_wrong_vb_mutation(), and wait_for_persisted_value().
static ENGINE_ERROR_CODE storeCasVb11 (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, const void * cookie, ENGINE_STORE_OPERATION op, const char * key, const char * value, size_t vlen, uint32_t flags, item ** outitem, uint64_t casIn, uint16_t vb) [static]
References check.
Referenced by store(), test_append(), test_prepend(), test_restart_bin_val(), test_set_change_flags(), and test_set_get_hit_bin().
static bool teardown (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References rmdb().
static enum test_result test_add (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), and store().
static enum test_result test_alloc_limit (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check.
static enum test_result test_append (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), and storeCasVb11().
static enum test_result test_bg_stats (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), evict_key(), get_int_stat(), and wait_for_persisted_value().
static enum test_result test_bug2509 (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, get_int_stat(), store(), and testHarness.
static enum test_result test_cas (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), and store().
static enum test_result test_conc_set (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References conc_del_set_thread(), get_int_stat(), testHarness, wait_for_flusher_to_settle(), and wait_for_persisted_value().
static enum test_result test_curr_items (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References add_response(), check, CMD_DEL_VBUCKET, create_packet(), get_int_stat(), last_status(), set_vbucket_state(), store(), verify_curr_items(), wait_for_flusher_to_settle(), and wait_for_stat_change().
static enum test_result test_db_shards (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References add_stats(), check, and get_int_stat().
static enum test_result test_delete (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), store(), and verify_key().
static enum test_result test_delete_set (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), testHarness, verify_key(), and wait_for_persisted_value().
static enum test_result test_disk_gt_ram_delete_paged_out (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, evict_key(), get_int_stat(), verify_key(), and wait_for_persisted_value().
static enum test_result test_disk_gt_ram_golden (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), evict_key(), get_int_stat(), wait_for_persisted_value(), and wait_for_stat_change().
static enum test_result test_disk_gt_ram_incr (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), evict_key(), get_int_stat(), and wait_for_persisted_value().
static enum test_result test_disk_gt_ram_incr_race (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References bg_incr_thread(), check_key_value(), evict_key(), get_int_stat(), set_flush_param(), wait_for_persisted_value(), and wait_for_stat_change().
static enum test_result test_disk_gt_ram_paged_rm (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, evict_key(), get_int_stat(), wait_for_persisted_value(), and wait_for_stat_change().
static enum test_result test_disk_gt_ram_rm_race (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References bg_del_thread(), check, evict_key(), get_int_stat(), set_flush_param(), verify_key(), and wait_for_persisted_value().
static enum test_result test_disk_gt_ram_set_race (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References bg_set_thread(), check_key_value(), evict_key(), get_int_stat(), set_flush_param(), and wait_for_persisted_value().
static enum test_result test_disk_gt_ram_update_paged_out (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), evict_key(), get_int_stat(), store(), and wait_for_persisted_value().
static enum test_result test_duplicate_items_disk (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References add_response(), check, check_key_value(), CMD_DEL_VBUCKET, create_packet(), evict_key(), get_int_stat(), last_status(), set_vbucket_state(), store(), verify_vbucket_missing(), wait_for_persisted_value(), and wait_for_stat_change().
static enum test_result test_expiry (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), get_int_stat(), and testHarness.
static enum test_result test_expiry_flush (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, get_int_stat(), and wait_for_stat_change().
static enum test_result test_expiry_loader (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), get_int_stat(), and testHarness.
static enum test_result test_flush (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), store(), and verify_key().
static enum test_result test_flush_multiv (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), set_vbucket_state(), store(), verify_key(), and verify_vb_key().
static enum test_result test_flush_multiv_restart (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), set_vbucket_state(), store(), testHarness, verify_key(), and verify_vbucket_missing().
static enum test_result test_flush_restart (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), store(), testHarness, and verify_key().
static enum test_result test_flush_stats (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), get_int_stat(), store(), verify_key(), and wait_for_stat_change().
static enum test_result test_get_miss (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, and verify_key().
static enum test_result test_incr (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), and store().
static enum test_result test_incr_default (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, and check_key_value().
static enum test_result test_incr_miss (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, and verify_key().
static enum test_result test_init_fail (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, and testHarness.
static enum test_result test_io_stats (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), evict_key(), get_int_stat(), and wait_for_persisted_value().
static enum test_result test_key_stats (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References add_stats(), check, set_vbucket_state(), store(), and testHarness.
static enum test_result test_max_size_settings (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, epsilon(), get_int_stat(), and set_flush_param().
static enum test_result test_mem_stats (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), evict_key(), get_int_stat(), and wait_for_persisted_value().
static enum test_result test_memory_limit (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), get_int_stat(), store(), and verify_key().
static enum test_result test_novb0 (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, and verify_vbucket_missing().
static enum test_result test_pending_vb_mutation (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, ENGINE_STORE_OPERATION op) [static]
References check, set_vbucket_state(), store(), testHarness, and verify_vbucket_state().
Referenced by test_vb_add_pending(), test_vb_append_pending(), test_vb_cas_pending(), test_vb_prepend_pending(), test_vb_replace_pending(), and test_vb_set_pending().
static enum test_result test_prepend (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), and storeCasVb11().
static enum test_result test_replace (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), and store().
static enum test_result test_replica_vb_mutation (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, ENGINE_STORE_OPERATION op) [static]
References check, get_int_stat(), set_vbucket_state(), store(), verify_vbucket_state(), and wait_for_stat_change().
Referenced by test_vb_add_replica(), test_vb_append_replica(), test_vb_cas_replica(), test_vb_prepend_replica(), test_vb_replace_replica(), and test_vb_set_replica().
static enum test_result test_restart (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), store(), and testHarness.
static enum test_result test_restart_bin_val (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), storeCasVb11(), and testHarness.
static enum test_result test_set (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, and store().
static enum test_result test_set_change_flags (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, get_value(), store(), and storeCasVb11().
static enum test_result test_set_delete (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), get_int_stat(), store(), verify_key(), and wait_for_flusher_to_settle().
static enum test_result test_set_get_hit (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), and store().
static enum test_result test_set_get_hit_bin (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, check_key_value(), and storeCasVb11().
static enum test_result test_stats (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References add_stats(), and check.
static enum test_result test_tap_ack_stream (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, get_key(), get_value(), store(), and testHarness.
static enum test_result test_tap_filter_stream (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, get_int_stat(), get_key(), set_vbucket_state(), store(), testHarness, and verify_item().
static enum test_result test_tap_rcvr_mutate (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, and check_key_value().
static enum test_result test_tap_rcvr_mutate_dead (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check.
static enum test_result test_tap_rcvr_mutate_pending (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, and set_vbucket_state().
static enum test_result test_tap_rcvr_mutate_replica (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, and set_vbucket_state().
static enum test_result test_tap_stream (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, decayingSleep(), evict_key(), get_int_stat(), get_key(), store(), testHarness, and verify_item().
static enum test_result test_validate_engine_handle (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check.
static enum test_result test_value_eviction (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References add_response(), check, check_key_value(), CMD_EVICT_KEY, create_packet(), evict_key(), get_int_stat(), last_status(), store(), and wait_for_persisted_value().
static enum test_result test_vb_add_pending (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_pending_vb_mutation().
static enum test_result test_vb_add_replica (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_replica_vb_mutation().
static enum test_result test_vb_append_pending (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_pending_vb_mutation().
static enum test_result test_vb_append_replica (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_replica_vb_mutation().
static enum test_result test_vb_cas_pending (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_pending_vb_mutation().
static enum test_result test_vb_cas_replica (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_replica_vb_mutation().
static enum test_result test_vb_del_pending (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, set_vbucket_state(), and testHarness.
static enum test_result test_vb_del_replica (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, get_int_stat(), set_vbucket_state(), and wait_for_stat_change().
static enum test_result test_vb_get_pending (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, set_vbucket_state(), and testHarness.
static enum test_result test_vb_get_replica (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, get_int_stat(), set_vbucket_state(), verify_vb_key(), and wait_for_stat_change().
static enum test_result test_vb_incr_pending (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, set_vbucket_state(), and testHarness.
static enum test_result test_vb_incr_replica (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, get_int_stat(), set_vbucket_state(), and wait_for_stat_change().
static enum test_result test_vb_prepend_pending (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_pending_vb_mutation().
static enum test_result test_vb_prepend_replica (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_replica_vb_mutation().
static enum test_result test_vb_replace_pending (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_pending_vb_mutation().
static enum test_result test_vb_replace_replica (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_replica_vb_mutation().
static enum test_result test_vb_set_pending (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_pending_vb_mutation().
static enum test_result test_vb_set_replica (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_replica_vb_mutation().
static enum test_result test_vbucket_create (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References set_vbucket_state(), verify_vbucket_missing(), and verify_vbucket_state().
static enum test_result test_vbucket_destroy (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References add_response(), check, CMD_DEL_VBUCKET, create_packet(), last_status(), set_vbucket_state(), and verify_vbucket_missing().
static enum test_result test_vbucket_destroy_restart (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References add_response(), check, check_key_value(), CMD_DEL_VBUCKET, create_packet(), last_status(), set_vbucket_state(), store(), testHarness, verify_vbucket_missing(), and verify_vbucket_state().
static enum test_result test_vbucket_destroy_stats (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References add_response(), check, CMD_DEL_VBUCKET, create_packet(), evict_key(), get_int_stat(), last_status(), set_vbucket_state(), store(), verify_vbucket_missing(), wait_for_persisted_value(), and wait_for_stat_change().
static enum test_result test_vbucket_get (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References verify_vbucket_state().
static enum test_result test_vbucket_get_miss (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References verify_vbucket_missing().
static enum test_result test_vkey_stats (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References add_stats(), check, set_vbucket_state(), testHarness, and wait_for_persisted_value().
static enum test_result test_whitespace_db (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References add_stats(), check, and WHITESPACE_DB.
static enum test_result test_wrong_vb_add (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_wrong_vb_mutation().
static enum test_result test_wrong_vb_append (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_wrong_vb_mutation().
static enum test_result test_wrong_vb_cas (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_wrong_vb_mutation().
static enum test_result test_wrong_vb_del (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, get_int_stat(), and wait_for_stat_change().
static enum test_result test_wrong_vb_get (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, get_int_stat(), verify_vb_key(), and wait_for_stat_change().
static enum test_result test_wrong_vb_incr (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References check, get_int_stat(), and wait_for_stat_change().
static enum test_result test_wrong_vb_mutation (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, ENGINE_STORE_OPERATION op) [static]
References check, get_int_stat(), store(), and wait_for_stat_change().
Referenced by test_wrong_vb_add(), test_wrong_vb_append(), test_wrong_vb_cas(), test_wrong_vb_prepend(), test_wrong_vb_replace(), and test_wrong_vb_set().
static enum test_result test_wrong_vb_prepend (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_wrong_vb_mutation().
static enum test_result test_wrong_vb_replace (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_wrong_vb_mutation().
static enum test_result test_wrong_vb_set (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References test_wrong_vb_mutation().
static void verify_curr_items (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, int exp, const char * msg) [static]
References get_int_stat().
Referenced by test_curr_items().
static enum test_result verify_item (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, item * i, const char * key, size_t klen, const char * val, size_t vlen) [static]
References check.
Referenced by test_tap_filter_stream(), and test_tap_stream().
static ENGINE_ERROR_CODE verify_key (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, const char * key) [static]
References verify_vb_key().
Referenced by test_delete(), test_delete_set(), test_disk_gt_ram_delete_paged_out(), test_disk_gt_ram_rm_race(), test_flush(), test_flush_multiv(), test_flush_multiv_restart(), test_flush_restart(), test_flush_stats(), test_get_miss(), test_incr_miss(), test_memory_limit(), and test_set_delete().
static ENGINE_ERROR_CODE verify_vb_key (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, const char * key, uint16_t vbucket) [static]
Referenced by test_flush_multiv(), test_vb_get_replica(), test_wrong_vb_get(), and verify_key().
static bool verify_vbucket_missing (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, uint16_t vb) [static]
References add_stats(), and check.
Referenced by test_duplicate_items_disk(), test_flush_multiv_restart(), test_novb0(), test_vbucket_create(), test_vbucket_destroy(), test_vbucket_destroy_restart(), test_vbucket_destroy_stats(), and test_vbucket_get_miss().
static bool verify_vbucket_state (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, uint16_t vb, const char * expected, bool mute = false) [static]
References add_response(), CMD_GET_VBUCKET, create_packet(), and last_status().
Referenced by test_pending_vb_mutation(), test_replica_vb_mutation(), test_vbucket_create(), test_vbucket_destroy_restart(), and test_vbucket_get().
static void wait_for_flusher_to_settle (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1) [static]
References decayingSleep(), and get_int_stat().
Referenced by test_conc_set(), test_curr_items(), test_set_delete(), and wait_for_persisted_value().
static void wait_for_persisted_value (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, const char * key, const char * val, uint16_t vbucketId = 0) [static]
References check, store(), and wait_for_flusher_to_settle().
Referenced by test_bg_stats(), test_conc_set(), test_delete_set(), test_disk_gt_ram_delete_paged_out(), test_disk_gt_ram_golden(), test_disk_gt_ram_incr(), test_disk_gt_ram_incr_race(), test_disk_gt_ram_paged_rm(), test_disk_gt_ram_rm_race(), test_disk_gt_ram_set_race(), test_disk_gt_ram_update_paged_out(), test_duplicate_items_disk(), test_io_stats(), test_mem_stats(), test_value_eviction(), test_vbucket_destroy_stats(), and test_vkey_stats().
static void wait_for_stat_change (ENGINE_HANDLE * h, ENGINE_HANDLE_V1 * h1, const char * stat, int initial) [static]
References decayingSleep(), and get_int_stat().
Referenced by test_curr_items(), test_disk_gt_ram_golden(), test_disk_gt_ram_incr_race(), test_disk_gt_ram_paged_rm(), test_duplicate_items_disk(), test_expiry_flush(), test_flush_stats(), test_replica_vb_mutation(), test_vb_del_replica(), test_vb_get_replica(), test_vb_incr_replica(), test_vbucket_destroy_stats(), test_wrong_vb_del(), test_wrong_vb_get(), test_wrong_vb_incr(), and test_wrong_vb_mutation().
Variable Documentation
char* last_body = NULL
char* last_key = NULL
struct test_harness testHarness
Referenced by setup_suite(), test_bug2509(), test_conc_set(), test_delete_set(), test_expiry(), test_expiry_loader(), test_flush_multiv_restart(), test_flush_restart(), test_init_fail(), test_key_stats(), test_pending_vb_mutation(), test_restart(), test_restart_bin_val(), test_tap_ack_stream(), test_tap_filter_stream(), test_tap_stream(), test_vb_del_pending(), test_vb_get_pending(), test_vb_incr_pending(), test_vbucket_destroy_restart(), and test_vkey_stats().
std::map<std::string, std::string> vals
Referenced by add_casted_stat(), and EventuallyPersistentEngine::arithmetic().