membase core engine: ep_engine.cc File Reference
ep_engine.cc File Reference
#include "config.h"
#include <limits>
#include <assert.h>
#include <fcntl.h>
#include <memcached/engine.h>
#include <memcached/protocol_binary.h>
#include "ep_engine.h"
Classes
class BackFillVisitor
VBucketVisitor to backfill a TapConnection.
struct histo_stat_adder< T >
class StatVBucketVisitor
Functions
static size_t percentOf (size_t val, double percent)
static EventuallyPersistentEngine * getHandle (ENGINE_HANDLE *handle)
Helper function to avoid typing in the long cast all over the place.
template<typename T >
static void validate (T v, T l, T h)
static const engine_info * EvpGetInfo (ENGINE_HANDLE *handle)
static ENGINE_ERROR_CODE EvpInitialize (ENGINE_HANDLE *handle, const char *config_str)
static void EvpDestroy (ENGINE_HANDLE *handle)
static ENGINE_ERROR_CODE EvpItemAllocate (ENGINE_HANDLE *handle, const void *cookie, item **item, const void *key, const size_t nkey, const size_t nbytes, const int flags, const rel_time_t exptime)
static ENGINE_ERROR_CODE EvpItemDelete (ENGINE_HANDLE *handle, const void *cookie, const void *key, const size_t nkey, uint64_t cas, uint16_t vbucket)
static void EvpItemRelease (ENGINE_HANDLE *handle, const void *cookie, item *item)
static ENGINE_ERROR_CODE EvpGet (ENGINE_HANDLE *handle, const void *cookie, item **item, const void *key, const int nkey, uint16_t vbucket)
static ENGINE_ERROR_CODE EvpGetStats (ENGINE_HANDLE *handle, const void *cookie, const char *stat_key, int nkey, ADD_STAT add_stat)
static ENGINE_ERROR_CODE EvpStore (ENGINE_HANDLE *handle, const void *cookie, item *item, uint64_t *cas, ENGINE_STORE_OPERATION operation, uint16_t vbucket)
static ENGINE_ERROR_CODE EvpArithmetic (ENGINE_HANDLE *handle, const void *cookie, const void *key, const int nkey, const bool increment, const bool create, const uint64_t delta, const uint64_t initial, const rel_time_t exptime, uint64_t *cas, uint64_t *result, uint16_t vbucket)
static ENGINE_ERROR_CODE EvpFlush (ENGINE_HANDLE *handle, const void *cookie, time_t when)
static void EvpResetStats (ENGINE_HANDLE *handle, const void *cookie)
static
protocol_binary_response_status stopFlusher (EventuallyPersistentEngine *e, const char **msg)
static
protocol_binary_response_status startFlusher (EventuallyPersistentEngine *e, const char **msg)
static
protocol_binary_response_status setTapParam (EventuallyPersistentEngine *e, const char *keyz, const char *valz, const char **msg)
static
protocol_binary_response_status setFlushParam (EventuallyPersistentEngine *e, const char *keyz, const char *valz, const char **msg)
static
protocol_binary_response_status evictKey (EventuallyPersistentEngine *e, protocol_binary_request_header *request, const char **msg)
static
protocol_binary_response_status setParam (EventuallyPersistentEngine *e, protocol_binary_request_header *request, const char **msg)
static
protocol_binary_response_status getVbucket (EventuallyPersistentEngine *e, protocol_binary_request_header *request, const char **msg)
static
protocol_binary_response_status setVbucket (EventuallyPersistentEngine *e, protocol_binary_request_header *request, const char **msg)
static
protocol_binary_response_status deleteVBucket (EventuallyPersistentEngine *e, protocol_binary_request_header *request, const char **msg)
static ENGINE_ERROR_CODE EvpUnknownCommand (ENGINE_HANDLE *handle, const void *cookie, protocol_binary_request_header *request, ADD_RESPONSE response)
static void EvpItemSetCas (ENGINE_HANDLE *handle, const void *cookie, item *item, uint64_t cas)
static ENGINE_ERROR_CODE EvpTapNotify (ENGINE_HANDLE *handle, const void *cookie, void *engine_specific, uint16_t nengine, uint8_t ttl, uint16_t tap_flags, tap_event_t tap_event, uint32_t tap_seqno, const void *key, size_t nkey, uint32_t flags, uint32_t exptime, uint64_t cas, const void *data, size_t ndata, uint16_t vbucket)
static tap_event_t EvpTapIterator (ENGINE_HANDLE *handle, const void *cookie, item **itm, void **es, uint16_t *nes, uint8_t *ttl, uint16_t *flags, uint32_t *seqno, uint16_t *vbucket)
static TAP_ITERATOR EvpGetTapIterator (ENGINE_HANDLE *handle, const void *cookie, const void *client, size_t nclient, uint32_t flags, const void *userdata, size_t nuserdata)
static void EvpHandleDisconnect (const void *cookie, ENGINE_EVENT_TYPE type, const void *event_data, const void *cb_data)
ENGINE_ERROR_CODE create_instance (uint64_t interface, GET_SERVER_API get_server_api, ENGINE_HANDLE **handle)
The only public interface to the eventually persistance engine.
void * EvpNotifyTapIo (void *arg)
static bool EvpGetItemInfo (ENGINE_HANDLE *handle, const void *cookie, const item *item, item_info *item_info)
EXTENSION_LOGGER_DESCRIPTOR * getLogger (void)
static void * launch_backfill_thread (void *arg)
static void add_casted_stat (const char *k, const char *v, ADD_STAT add_stat, const void *cookie)
static void add_casted_stat (const char *k, uint64_t v, ADD_STAT add_stat, const void *cookie)
template<typename T >
static void add_casted_stat (const char *k, const Atomic< T > &v, ADD_STAT add_stat, const void *cookie)
template<typename T >
static void add_casted_stat (const char *k, const Histogram< T > &v, ADD_STAT add_stat, const void *cookie)
template<typename T >
static void addTapStat (const char *name, const TapConnection *tc, T val, ADD_STAT add_stat, const void *cookie)
static void addTapStat (const char *name, const TapConnection *tc, bool val, ADD_STAT add_stat, const void *cookie)
static void doDispatcherStat (const char *prefix, const DispatcherState &ds, const void *cookie, ADD_STAT add_stat)
Variables
static SERVER_EXTENSION_API * extensionApi
Function Documentation
static void add_casted_stat (const char * k, const char * v, ADD_STAT add_stat, const void * cookie) [static]
Referenced by add_casted_stat(), addTapStat(), doDispatcherStat(), histo_stat_adder< T >::operator()(), and StatVBucketVisitor::visitBucket().
static void add_casted_stat (const char * k, uint64_t v, ADD_STAT add_stat, const void * cookie) [static]
References add_casted_stat(), and vals.
template<typename T > static void add_casted_stat (const char * k, const Atomic< T > & v, ADD_STAT add_stat, const void * cookie) [static]
References add_casted_stat(), and Atomic< T >::get().
template<typename T > static void add_casted_stat (const char * k, const Histogram< T > & v, ADD_STAT add_stat, const void * cookie) [static]
References Histogram< T >::begin(), and Histogram< T >::end().
template<typename T > static void addTapStat (const char * name, const TapConnection * tc, T val, ADD_STAT add_stat, const void * cookie) [static]
References add_casted_stat(), and TapConnection::getName().
Referenced by addTapStat().
static void addTapStat (const char * name, const TapConnection * tc, bool val, ADD_STAT add_stat, const void * cookie) [static]
References addTapStat().
ENGINE_ERROR_CODE create_instance (uint64_t interface, GET_SERVER_API get_server_api, ENGINE_HANDLE ** handle)
The only public interface to the eventually persistance engine.
Allocate a new instance and initialize it
Parameters:
interface the highest interface the server supports (we only support interface 1)
get_server_api callback function to get the server exported API functions
handle Where to return the new instance
Returns:
ENGINE_SUCCESS on success
References ep_abs_time, and ep_current_time.
static protocol_binary_response_status deleteVBucket (EventuallyPersistentEngine * e, protocol_binary_request_header * request, const char ** msg) [static]
References EventuallyPersistentEngine::deleteVBucket(), EventuallyPersistentEngine::getVBucket(), and parseUint16().
Referenced by EvpUnknownCommand().
static void doDispatcherStat (const char * prefix, const DispatcherState & ds, const void * cookie, ADD_STAT add_stat) [static]
References add_casted_stat(), gethrtime(), DispatcherState::getStateName(), DispatcherState::getTaskName(), DispatcherState::getTaskStart(), and DispatcherState::isRunningTask().
static protocol_binary_response_status evictKey (EventuallyPersistentEngine * e, protocol_binary_request_header * request, const char ** msg) [static]
References EventuallyPersistentEngine::evictKey(), and getLogger().
Referenced by EvpUnknownCommand().
static ENGINE_ERROR_CODE EvpArithmetic (ENGINE_HANDLE * handle, const void * cookie, const void * key, const int nkey, const bool increment, const bool create, const uint64_t delta, const uint64_t initial, const rel_time_t exptime, uint64_t * cas, uint64_t * result, uint16_t vbucket) [static]
References EventuallyPersistentEngine::arithmetic(), and getHandle().
static void EvpDestroy (ENGINE_HANDLE * handle) [static]
References EventuallyPersistentEngine::destroy(), and getHandle().
static ENGINE_ERROR_CODE EvpFlush (ENGINE_HANDLE * handle, const void * cookie, time_t when) [static]
References EventuallyPersistentEngine::flush(), and getHandle().
static ENGINE_ERROR_CODE EvpGet (ENGINE_HANDLE * handle, const void * cookie, item ** item, const void * key, const int nkey, uint16_t vbucket) [static]
References EventuallyPersistentEngine::get(), and getHandle().
static const engine_info* EvpGetInfo (ENGINE_HANDLE * handle) [static]
References getHandle(), and EventuallyPersistentEngine::getInfo().
static bool EvpGetItemInfo (ENGINE_HANDLE * handle, const void * cookie, const item * item, item_info * item_info) [static]
References Item::getCas(), Item::getData(), Item::getExptime(), Item::getFlags(), Item::getKey(), Item::getNBytes(), and Item::getNKey().
static ENGINE_ERROR_CODE EvpGetStats (ENGINE_HANDLE * handle, const void * cookie, const char * stat_key, int nkey, ADD_STAT add_stat) [static]
References getHandle(), and EventuallyPersistentEngine::getStats().
static TAP_ITERATOR EvpGetTapIterator (ENGINE_HANDLE * handle, const void * cookie, const void * client, size_t nclient, uint32_t flags, const void * userdata, size_t nuserdata) [static]
References EventuallyPersistentEngine::createTapQueue(), and getHandle().
static void EvpHandleDisconnect (const void * cookie, ENGINE_EVENT_TYPE type, const void * event_data, const void * cb_data) [static]
References getHandle(), and EventuallyPersistentEngine::handleDisconnect().
Referenced by EventuallyPersistentEngine::initialize().
static ENGINE_ERROR_CODE EvpInitialize (ENGINE_HANDLE * handle, const char * config_str) [static]
References getHandle(), and EventuallyPersistentEngine::initialize().
static ENGINE_ERROR_CODE EvpItemAllocate (ENGINE_HANDLE * handle, const void * cookie, item ** item, const void * key, const size_t nkey, const size_t nbytes, const int flags, const rel_time_t exptime) [static]
References getHandle(), and EventuallyPersistentEngine::itemAllocate().
static ENGINE_ERROR_CODE EvpItemDelete (ENGINE_HANDLE * handle, const void * cookie, const void * key, const size_t nkey, uint64_t cas, uint16_t vbucket) [static]
References getHandle(), and EventuallyPersistentEngine::itemDelete().
static void EvpItemRelease (ENGINE_HANDLE * handle, const void * cookie, item * item) [static]
References getHandle(), and EventuallyPersistentEngine::itemRelease().
static void EvpItemSetCas (ENGINE_HANDLE * handle, const void * cookie, item * item, uint64_t cas) [static]
void* EvpNotifyTapIo (void * arg)
static void EvpResetStats (ENGINE_HANDLE * handle, const void * cookie) [static]
References getHandle(), and EventuallyPersistentEngine::resetStats().
static ENGINE_ERROR_CODE EvpStore (ENGINE_HANDLE * handle, const void * cookie, item * item, uint64_t * cas, ENGINE_STORE_OPERATION operation, uint16_t vbucket) [static]
References getHandle(), and EventuallyPersistentEngine::store().
static tap_event_t EvpTapIterator (ENGINE_HANDLE * handle, const void * cookie, item ** itm, void ** es, uint16_t * nes, uint8_t * ttl, uint16_t * flags, uint32_t * seqno, uint16_t * vbucket) [static]
References getHandle(), and EventuallyPersistentEngine::walkTapQueue().
static ENGINE_ERROR_CODE EvpTapNotify (ENGINE_HANDLE * handle, const void * cookie, void * engine_specific, uint16_t nengine, uint8_t ttl, uint16_t tap_flags, tap_event_t tap_event, uint32_t tap_seqno, const void * key, size_t nkey, uint32_t flags, uint32_t exptime, uint64_t cas, const void * data, size_t ndata, uint16_t vbucket) [static]
References getHandle(), and EventuallyPersistentEngine::tapNotify().
static ENGINE_ERROR_CODE EvpUnknownCommand (ENGINE_HANDLE * handle, const void * cookie, protocol_binary_request_header * request, ADD_RESPONSE response) [static]
References CMD_DEL_VBUCKET, CMD_EVICT_KEY, CMD_GET_VBUCKET, CMD_SET_FLUSH_PARAM, CMD_SET_TAP_PARAM, CMD_SET_VBUCKET, CMD_START_PERSISTENCE, CMD_STOP_PERSISTENCE, deleteVBucket(), EPStats::delVbucketCmdHisto, evictKey(), EventuallyPersistentEngine::getEpStats(), getHandle(), getVbucket(), EPStats::getVbucketCmdHisto, setParam(), setVbucket(), EPStats::setVbucketCmdHisto, startFlusher(), and stopFlusher().
static EventuallyPersistentEngine* getHandle (ENGINE_HANDLE * handle) [inline, static]
Helper function to avoid typing in the long cast all over the place.
Parameters:
handle pointer to the engine
Returns:
the engine as a class
Referenced by EvpArithmetic(), EvpDestroy(), EvpFlush(), EvpGet(), EvpGetInfo(), EvpGetStats(), EvpGetTapIterator(), EvpHandleDisconnect(), EvpInitialize(), EvpItemAllocate(), EvpItemDelete(), EvpItemRelease(), EvpResetStats(), EvpStore(), EvpTapIterator(), EvpTapNotify(), and EvpUnknownCommand().
EXTENSION_LOGGER_DESCRIPTOR* getLogger (void)
References extensionApi.
Referenced by VBucketHolder::addBucket(), EventuallyPersistentStore::bgFetch(), ExpiredItemPager::callback(), ItemPager::callback(), LoadStorageKVPairCallback::callback(), EventuallyPersistentStore::completeBGFetch(), EventuallyPersistentStore::completeSetVBState(), EventuallyPersistentStore::completeVBucketDeletion(), EventuallyPersistentEngine::createTapQueue(), SqliteStrategy::doFile(), SqliteEvaluator::eval(), evictKey(), EventuallyPersistentEngine::handleDisconnect(), Flusher::initialize(), GetlExtension::initialize(), EventuallyPersistentEngine::initialize(), launch_dispatcher_thread(), Dispatcher::run(), VBucket::setState(), EventuallyPersistentEngine::startFlusher(), Flusher::step(), Dispatcher::stop(), EventuallyPersistentEngine::stopFlusher(), EventuallyPersistentStore::warmup(), Flusher::~Flusher(), and VBucket::~VBucket().
static protocol_binary_response_status getVbucket (EventuallyPersistentEngine * e, protocol_binary_request_header * request, const char ** msg) [static]
References EventuallyPersistentEngine::getVBucket(), and parseUint16().
Referenced by EvpUnknownCommand().
static void* launch_backfill_thread (void * arg) [static]
Referenced by EventuallyPersistentEngine::queueBackfill().
static size_t percentOf (size_t val, double percent) [static]
Referenced by EventuallyPersistentEngine::initialize(), and setFlushParam().
static protocol_binary_response_status setFlushParam (EventuallyPersistentEngine * e, const char * keyz, const char * valz, const char ** msg) [static]
References EventuallyPersistentEngine::getEpStats(), StoredValue::getMaxDataSize(), MAX_BG_FETCH_DELAY, MAX_DATA_AGE_PARAM, MAX_TXN_SIZE, EPStats::maxDataSize, EPStats::mem_high_wat, EPStats::mem_low_wat, percentOf(), EventuallyPersistentEngine::setBGFetchDelay(), EventuallyPersistentEngine::setMinDataAge(), EventuallyPersistentEngine::setQueueAgeCap(), EventuallyPersistentEngine::setTxnSize(), and validate().
Referenced by setParam().
static protocol_binary_response_status setParam (EventuallyPersistentEngine * e, protocol_binary_request_header * request, const char ** msg) [static]
References CMD_SET_FLUSH_PARAM, CMD_SET_TAP_PARAM, setFlushParam(), and setTapParam().
Referenced by EvpUnknownCommand().
static protocol_binary_response_status setTapParam (EventuallyPersistentEngine * e, const char * keyz, const char * valz, const char ** msg) [static]
Referenced by setParam().
static protocol_binary_response_status setVbucket (EventuallyPersistentEngine * e, protocol_binary_request_header * request, const char ** msg) [static]
References parseUint16(), and EventuallyPersistentEngine::setVBucketState().
Referenced by EvpUnknownCommand().
static protocol_binary_response_status startFlusher (EventuallyPersistentEngine * e, const char ** msg) [static]
References EventuallyPersistentEngine::startFlusher().
Referenced by EvpUnknownCommand().
static protocol_binary_response_status stopFlusher (EventuallyPersistentEngine * e, const char ** msg) [static]
References EventuallyPersistentEngine::stopFlusher().
Referenced by EvpUnknownCommand().
template<typename T > static void validate (T v, T l, T h) [static]
Referenced by setFlushParam().
Variable Documentation
SERVER_EXTENSION_API* extensionApi [static]
Referenced by getLogger().