membase core engine: gethrtime.c File Reference
gethrtime.c File Reference
#include "config.h"
#include <stdlib.h>
#include <time.h>
#include <sys/time.h>
#include <assert.h>
#include <mach/mach_time.h>
Defines
#define CLOCK_MONOTONIC 192996728
#define HAVE_CLOCK_GETTIME 1
Functions
static void mach_absolute_difference (uint64_t start, uint64_t end, struct timespec *tp)
static int clock_gettime (int which, struct timespec *tp)
hrtime_t gethrtime (void)
Define Documentation
#define CLOCK_MONOTONIC 192996728
Referenced by clock_gettime(), and gethrtime().
#define HAVE_CLOCK_GETTIME 1
Function Documentation
static int clock_gettime (int which, struct timespec * tp) [static]
References CLOCK_MONOTONIC, and mach_absolute_difference().
Referenced by gethrtime().
hrtime_t gethrtime (void)
References clock_gettime(), and CLOCK_MONOTONIC.
Referenced by VBucket::addPendingOp(), TapBGFetchCallback::callback(), BGFetchCallback::callback(), EventuallyPersistentStore::completeBGFetch(), doDispatcherStat(), Dispatcher::run(), and BlockTimer::~BlockTimer().
static void mach_absolute_difference (uint64_t start, uint64_t end, struct timespec * tp) [static]
Referenced by clock_gettime().