membase core engine: sizes.cc File Reference
sizes.cc File Reference
#include "config.h"
#include <stdio.h>
#include "item.hh"
#include "stored-value.hh"
#include "ep.hh"
#include "vbucket.hh"
#include "histo.hh"
Functions
static void display (const char *name, size_t size)
int main (int argc, char **argv)
Function Documentation
static void display (const char * name, size_t size) [static]
Referenced by main().
int main (int argc, char ** argv)
References display(), GIGANTOR, and StoredValue::sizeOf().