membase core engine: stored-value.hh File Reference
stored-value.hh File Reference
#include <climits>
#include <cstring>
#include <algorithm>
#include "common.hh"
#include "item.hh"
#include "locks.hh"
#include "stats.hh"
Classes
struct small_data
StoredValue "small" data storage.
struct feature_data
StoredValue "featured" data type.
union stored_value_bodies
Union of StoredValue data.
union blobval
Contents stored when swapped out.
class StoredValue
In-memory storage for an item.
class HashTableVisitor
Base class for visiting a hash table.
class HashTableDepthVisitor
Hash table visitor that reports the depth of each hashtable bucket.
class HashTableDepthStatVisitor
Hash table visitor that finds the min and max bucket depths.
class HashTableStatVisitor
Hash table visitor that collects stats of what's inside.
class VisitorTracker
Track the current number of hashtable visitors.
class StoredValueFactory
Creator of StoredValue instances.
class HashTable
A container of StoredValue instances.
Enumerations
enum mutation_type_t {
INVALID_VBUCKET, NOT_FOUND, INVALID_CAS, WAS_CLEAN,
WAS_DIRTY, IS_LOCKED, NOMEM
}
Mutation types as returned by store commands.
enum add_type_t { ADD_SUCCESS, ADD_NOMEM, ADD_EXISTS, ADD_UNDEL }
Result from add operation.
enum stored_value_type { small, featured }
Types of stored values.
Variables
rel_time_t(* ep_current_time)()
Enumeration Type Documentation
enum add_type_t
Result from add operation.
Enumerator:
ADD_SUCCESS
Add was successful.
ADD_NOMEM
No memory for operation.
ADD_EXISTS
Did not update -- item exists with this key.
ADD_UNDEL
Undeletes an existing dirty item.
enum mutation_type_t
Mutation types as returned by store commands.
Enumerator:
INVALID_VBUCKET
Storage was attempted on a vbucket not managed by this node.
NOT_FOUND
The item was not found for update.
INVALID_CAS
The wrong CAS identifier was sent for a CAS update.
WAS_CLEAN
The item was clean before this mutation.
WAS_DIRTY
This item was already dirty before this mutation.
IS_LOCKED
The item is locked and can't be updated.
NOMEM
Insufficient memory to store this item.
enum stored_value_type
Types of stored values.
Enumerator:
small
Small (minimally featured) stored values.
featured
Full featured stored values.
Variable Documentation
rel_time_t(* ep_current_time)()
Referenced by create_instance(), default_abs_time(), ep_real_time(), EventuallyPersistentStore::get(), StoredValue::markDirty(), HashTable::set(), and HashTable::unlocked_del().