membase core engine: histo_stat_adder< T > Struct Template Reference
histo_stat_adder< T > Struct Template Reference
Public Member Functions
histo_stat_adder (const char *k, ADD_STAT a, const void *c)
void operator() (const HistogramBin< T > *b)
Public Attributes
const char * prefix
ADD_STAT add_stat
const void * cookie
template<typename T>
struct histo_stat_adder< T >
Constructor & Destructor Documentation
template<typename T> histo_stat_adder< T >::histo_stat_adder (const char * k, ADD_STAT a, const void * c) [inline]
Member Function Documentation
template<typename T> void histo_stat_adder< T >::operator() (const HistogramBin< T > * b) [inline]
References add_casted_stat(), histo_stat_adder< T >::add_stat, HistogramBin< T >::count(), HistogramBin< T >::end(), histo_stat_adder< T >::prefix, and HistogramBin< T >::start().
Member Data Documentation
template<typename T> ADD_STAT histo_stat_adder< T >::add_stat
Referenced by histo_stat_adder< T >::operator()().
template<typename T> const void* histo_stat_adder< T >::cookie
template<typename T> const char* histo_stat_adder< T >::prefix
Referenced by histo_stat_adder< T >::operator()().
The documentation for this struct was generated from the following file:
ep_engine.cc